export enum WebSocketEventName {
  BVM_SUBSCRIBE_ADDRESS = 'BVM_SUBSCRIBE_ADDRESS',
  GROUP_STREAM_AI_REPLY_START = 'GROUP_STREAM_AI_REPLY_START',
  GROUP_STREAM_AI_REPLY = 'GROUP_STREAM_AI_REPLY',
  GROUP_STREAM_AI_REPLY_END = 'GROUP_STREAM_AI_REPLY_END',
}