export const BVM_GOVERNOR_ADDRESS =
  process.env.NEXT_PUBLIC_BVM_GOVERNOR_ADDRESS!;
export const BVM_TREASURY_ADDRESS =
  process.env.NEXT_PUBLIC_BVM_TREASURY_ADDRESS!;
export const BVM_TOKEN_ADDRESS = process.env.NEXT_PUBLIC_BVM_TOKEN_ADDRESS!;
export const SHARD_TOKEN_ADDRESS = process.env.NEXT_PUBLIC_SHARD_TOKEN_ADDRESS!;
