export const EVENT_LABEL = {
  GET_STARTED: 'get-started',
  SUBMIT_TIER1: 'submit - tier1',
  CUSTOMIZE_TIER2: 'customize - tier2',
  CUSTOMIZE_TIER3: 'customize - tier3',
  SUBMIT_TIER2: 'submit - tier2',
  SUBMIT_TIER3: 'submit - tier3',
  CONTACTS_US: 'contact - us',
  SUBMIT_CONTACT_US: 'submit - contact - us',
  PAYNOW: 'paynow',
  DEVELOPER_GUIDES: 'Developer guides',
  POC_CLICK_PRACTICE: 'poc - practice',
  POC_CLICK_JOIN_COMMUNITY: 'poc - join - community',
  POC_CLICK_CLOSE_PREPARE: 'poc - close - prepare',
  POC_SUBMIT_PROBLEM: 'poc - submit - problem',
  POC_SUBMIT_PROBLEM_SUCCESS: 'poc - submit - problem - success',
  POC_SUBMIT_PROBLEM_FAIL: 'poc - submit - problem - fail',
  POC_SUBMIT_PROBLEM_SELECT_TOPIC: 'poc - submit - problem - select - topic',
  POC_SELECT_TAB_PROBLEM: 'poc - select - tab - problem',
  POC_EXPORT_PRIVATE_KEY: 'poc - export - private key',
  POC_SET_UP_ENV: 'poc - set up your development environment',
};
