export const API_RESPONE = {
  error: null,
  status: false,
  result: [
    {
      id: '668f8ebe88f822fe3ebd346e',
      created_at: '2024-07-11T07:50:22.365Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'network',
      title: 'Networks',
      required: true,
      tooltip:
        'Choose whether to test on the testnet for trials and development or deploy on the mainnet for production and live use.',
      options: [
        {
          key: 'mainnet',
          title: 'Mainnet',
          value: 1,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: '',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'testnet',
          title: 'Testnet',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: '',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-testnet.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#FF7A41',
      type: 'module',
      disable: false,
      hidden: true,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 1,
    },
    {
      id: '668f8ebf88f822fe3ebd346f',
      created_at: '2024-07-11T07:50:23.442Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'hardware',
      title: 'Hardware',
      required: true,
      tooltip:
        'Select your hardware configuration to match the specific needs of your blockchain. Consider factors such as RAM, CPU cores, and storage capacity to ensure optimal performance and scalability.',
      options: [
        {
          key: '16g',
          title: '16 GB RAM, 8 cores, 320 GB SSD',
          value: 16785728,
          valueStr: '1',
          selectable: true,
          hidden: false,
          priceUSD: 99,
          priceBVM: 235,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: '32g',
          title: '32 GB RAM, 16 cores, 400 GB SSD',
          value: 33571216,
          valueStr: '2',
          selectable: true,
          hidden: false,
          priceUSD: 499,
          priceBVM: 1185,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: '64g',
          title: '64 GB RAM, 32 cores, 650 GB SSD',
          value: 67142282,
          valueStr: '3',
          selectable: true,
          hidden: false,
          priceUSD: 699,
          priceBVM: 1660,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#12DAC2',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 2,
    },
    {
      id: '668f8ebf88f822fe3ebd3470',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'settlement',
      title: 'Base Chains',
      required: true,
      tooltip:
        'Select the base layer on which you want to build your blockchain. This will determine the base protocol and network characteristics, such as security, scalability, and consensus mechanisms.',
      options: [
        {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'fractal',
          title: 'Fractal',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'testnet',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer1', 'layer2', 'layer2_hybrid'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/ic-fractal.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'doge',
          title: 'Doge',
          value: 0,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/ic-doge.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#F8B200',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Base Chain',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 0,
    },
    {
      id: '668f8ebf88f822fe3ebd3471',
      created_at: '2024-07-11T07:50:23.694Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'compute',
      title: 'Rollups',
      required: false,
      tooltip:
        'Choose the scaling solution tailored to your needs. Rollups enhance scalability and reduce transaction costs by processing transactions off-chain while posting transaction data on-chain.',
      options: [
        {
          key: 'zk',
          title: 'ZK Rollup',
          value: 21,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip:
            'Offer even higher scalability and cost-efficiency by bundling many transactions into a single proof. Provide strong security through zero-knowledge proofs, enabling fast finality and enhanced privacy. Can be done automatically.',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer2', 'layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'op',
          title: 'Optimistic Rollup',
          value: 20,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip:
            'Significantly increase transaction throughput and reduce costs. EVM-compatible and secure. <b>Need to contact the team to deploy</b>.',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer2', 'layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-op.svg',
          logo: '',
          setupLogo: '',
          needContactUs: true,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'gpu',
          title: 'GPU Rollup',
          value: 22,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: '',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'sovereign',
          title: 'Sovereign Rollup',
          value: 22,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: 'layer1',
          supportLayers: ['layer1'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-sov.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#A041FF',
      type: 'module',
      disable: true,
      hidden: true,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 3,
    },
    {
      id: '668f8ebf88f822fe3ebd3472',
      created_at: '2024-07-11T07:50:23.774Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'storage',
      title: 'Data Availability',
      required: true,
      tooltip:
        'Ensure easy access to transaction details and smart contracts for all nodes on L1, L2, and even L3 networks. Using a separate DA layer reduces mainnet congestion, enhancing scalability, security, and transaction cost-efficiency.',
      options: [
        {
          key: 'fractal',
          title: 'Fractal',
          value: 22,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'testnet',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer1', 'layer2', 'layer2_hybrid'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/ic-fractal.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'celestia',
          title: 'Celestia',
          value: 13,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: 'layer3',
          supportLayers: ['layer2_op', 'layer2_hybrid', 'layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-ceslestia.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'filecoin',
          title: 'Filecoin',
          value: 21,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 10,
          priceBVM: 25,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: 'layer3',
          supportLayers: ['layer2_op', 'layer2_hybrid'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-filecoin.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'bvm_da',
          title: 'Bitcoin',
          value: 21,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 3000,
          priceBVM: 7115,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer1', 'layer2'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          logo: '',
          setupLogo: '',
          needContactUs: true,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'polygon',
          title: 'Polygon',
          value: 10,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer2_op', 'layer2_hybrid'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-polygon.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'avail',
          title: 'Avail',
          value: 18,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 10,
          priceBVM: 25,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'testnet',
          requiredFor: null,
          supportLayer: 'layer3',
          supportLayers: ['layer2_op', 'layer2_hybrid'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-avail.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'near_da',
          title: 'Near',
          value: 15,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer2_op', 'layer2_hybrid'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-near.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#15C888',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'DA',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 4,
    },
    {
      id: '668f8ebf88f822fe3ebd3473',
      created_at: '2024-07-11T07:50:23.844Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'zk_prover',
      title: 'Prover',
      required: false,
      tooltip:
        "Prover is a crucial component responsible for generating cryptographic proofs that verify the correctness of transactions processed off-chain by the blockchain's sequencer.",
      options: [
        {
          key: 'zk_prover',
          title: 'ZK Prover',
          value: 1,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 1300,
          priceBVM: 3085,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: '',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer2', 'layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#15BDC8',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 7,
    },
    {
      id: '668f8ebf88f822fe3ebd3474',
      created_at: '2024-07-11T07:50:23.919Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'block_gas_limit',
      title: 'Gas',
      required: true,
      tooltip:
        'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
      options: [
        {
          key: '1m',
          title: '1,000,000,000',
          value: 1000000000,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-min.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: '2m',
          title: '2,000,000,000',
          value: 2000000000,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 5,
          priceBVM: 15,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-medium.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: '4m',
          title: '4,000,000,000',
          value: 4000000000,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 10,
          priceBVM: 25,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-max.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#FB9F00',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Block Gas Limit',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 5,
    },
    {
      id: '668f8ebf88f822fe3ebd3475',
      created_at: '2024-07-11T07:50:23.993Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'withdrawal_time',
      title: 'Withdrawals',
      required: true,
      tooltip:
        'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to the L1.',
      options: [
        {
          key: 'withdrawal_time_3',
          title: '24-hour',
          value: 86400,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3', 'layer2', 'layer2_hybrid', 'layer2_op'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-slow.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'withdrawal_time_2',
          title: '12-hour',
          value: 43200,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 100,
          priceBVM: 240,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3', 'layer2', 'layer2_hybrid', 'layer2_op'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-fast.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'withdrawal_time_1',
          title: '6-hour',
          value: 21600,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 300,
          priceBVM: 715,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3', 'layer2', 'layer2_hybrid', 'layer2_op'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-superfast.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'withdrawal_time_0',
          title: '1-hour',
          value: 3600,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 50,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: 'layer1',
          supportLayers: ['layer1'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-superfast.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#F200F2',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Withdrawal Time',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 6,
    },
    {
      id: '668f8ec088f822fe3ebd3476',
      created_at: '2024-07-11T07:50:24.072Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'wallet',
      title: 'UX',
      required: false,
      tooltip:
        'This module enhances user experience by allowing gas fees to be paid in different cryptocurrencies, eliminating the need to hold a specific one for transaction fees.',
      options: [
        {
          key: 'account_abstraction',
          title: 'Account Abstraction',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-wallet.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/account_abstraction_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_account_abstraction_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: true,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#00C1CD',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: true,
      whitelistAddress: [
        '0x4d0c64c6e576ad9206f87ac5e2d295043ba0ce8d',
        '0x63f674814Ab1329f05D2B9237Bc03C9c87ded2Aa',
        '0x4113ed747047863Ea729f30C1164328D9Cc8CfcF',
      ],
      isChain: false,
      order: 8,
    },
    {
      id: '668f8ec088f822fe3ebd3477',
      created_at: '2024-07-11T07:50:24.179Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'bridge_apps',
      title: 'Bridges',
      required: false,
      tooltip:
        'Bring BTC, ETH, SOL, BNB and other assets to your blockchain and transfer them back to Bitcoin and Ethereum networks.',
      options: [
        {
          key: 'btc_bridge',
          title: 'Bitcoin',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/btc_bridge_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'eth_bridge',
          title: 'Ethereum',
          value: 1,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/eth_bridge_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'solana_bridge',
          title: 'Solana',
          value: 2,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'mainnet',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-solana.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/solana_bridge_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'bsc_bridge',
          title: 'BSC',
          value: 2,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'mainnet',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-bsc.svg',
          logo: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-bsc.svg',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'runes_bridge',
          title: 'Runes',
          value: 3,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'mainnet',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-runes.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/runs_bridge_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'ordinals_bridge',
          title: 'Ordinals',
          value: 4,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'mainnet',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-ordinals.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/ordinals_bridge_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#855AFF',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: true,
      confuseWord: true,
      confuseIcon:
        'https://storage.googleapis.com/bvm-network/icons-tool/icon-bridge-confused.svg',
      confuseTitle: 'Your chain',
      updatable: true,
      whitelistAddress: null,
      isChain: false,
      order: 9,
    },
    {
      id: '668f8ec088f822fe3ebd3478',
      created_at: '2024-07-11T07:50:24.299Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'defi_apps',
      title: 'DeFi',
      required: false,
      tooltip:
        'Pre-install DeFi dapps to your blockchain, including token issuance, DEX, staking, and more to boost liquidity and attract users with essential financial services from the start.',
      options: [
        {
          key: 'create_token',
          title: 'Issue a token',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/token_issue_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_issue_token_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'vesting',
          title: 'Vesting',
          value: 1,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-vesting.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'staking',
          title: 'Staking',
          value: 2,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-staking.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/staking_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_staking_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: true,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'dex',
          title: 'DEX',
          value: 3,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-dex.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'orderbook',
          title: 'Orderbook',
          value: 4,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/order_book_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'perpeptual',
          title: 'Perpeptual',
          value: 5,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-perceptual.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'airdrop',
          title: 'Airdrop',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/token_issue_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_issue_token_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'white_paper',
          title: 'White Paper',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/image/ic-whitepaper.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/token_issue_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_issue_token_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#F76649',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: true,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: true,
      whitelistAddress: [
        '0x4d0c64c6e576ad9206f87ac5e2d295043ba0ce8d',
        '0x63f674814Ab1329f05D2B9237Bc03C9c87ded2Aa',
        '0x4113ed747047863Ea729f30C1164328D9Cc8CfcF',
        '0xc7bce55e89e8a5b55e9c833a6b0959b5d6686c9b',
        '0x1f3221451d8a80374d86ba76f07e08c056e74ce4',
        '0x742ad79fd4ed0657d66dd33e586d67a37a5518e9',
        '0x0a07ce4989de012bc74e2a75bc50a9a378f6967b',
      ],
      isChain: false,
      order: 10,
    },
    {
      id: '668f8ec088f822fe3ebd3479',
      created_at: '2024-07-11T07:50:24.462Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'degen_apps',
      title: 'Degens',
      required: false,
      tooltip:
        'Pre-install degen dapps to your blockchain to attract attention and increase user engagement.',
      options: [
        {
          key: 'wallet_type',
          title: 'Wallet',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'yologame',
          title: 'YOLO',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'nft_raffle',
          title: 'NFT Raffle',
          value: 1,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-raffle.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'mr_market',
          title: 'Mr. Markets',
          value: 2,
          valueStr: '',
          selectable: false,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-bull-bear.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#E6004D',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: true,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: [
        '0x2d66881F48Fe18c63C0CB52b3559FBf520287b2F',
        '0xb262df097f649cb962b6ee256b19eec51d77cfa8',
        '0x1f3221451d8a80374d86ba76f07e08c056e74ce4',
      ],
      isChain: false,
      order: 11,
    },
    {
      id: '668f8ec088f822fe3ebd347a',
      created_at: '2024-07-11T07:50:24.535Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'gaming_apps',
      title: 'Games',
      required: false,
      tooltip:
        'Pre-install gaming dapps for a fun and immersive experience. Introduce users to new and exciting on-chain games.',
      options: [
        {
          key: 'game_pepe',
          title: 'Pepe Fight',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'game_sum21',
          title: 'Sum21',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'game_merge',
          title: 'Merge',
          value: 1,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'game_blast',
          title: 'Blast',
          value: 2,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'game_connect',
          title: 'Connect',
          value: 3,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#C000E6',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: true,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: [
        '0x2d66881F48Fe18c63C0CB52b3559FBf520287b2F',
        '0xb262df097f649cb962b6ee256b19eec51d77cfa8',
      ],
      isChain: true,
      order: 12,
    },
    {
      id: '66ab4cb5ab0ec87655a8e084',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'layers',
      title: 'Scaling Solutions',
      required: true,
      tooltip:
        "<h2>Bitcoin Layer 1 (L1):</h2>\n          <h3>EVM Metaprotocol: </h3>\n          Enables the deployment of EVM-compatible smart contracts while leveraging Bitcoin's security. Ideal for\n          developers familiar with Ethereum tools who seek the stability and security of Bitcoin.\n          <br />\n          <i>Est time: 48h</i>\n          <br /><br />\n          <h2>Bitcoin Layer 2 (L2): </h2>\n          <h3>ZK Rollup:</h3>\n          Implements Zero-Knowledge (ZK) technology on Bitcoin as the base layer to enhance scalability and transaction\n          efficiency. This option is perfect for developers focused on scaling while maintaining top-tier security on\n          Bitcoin’s L1.\n          <br />\n          <i>Est time: 1h</i>        \n         \n          <br /><br />\n          <h3>Optimistic Rollup:</h3>\n          Processes transactions off-chain under the assumption of validity, which lowers costs and boosts scalability.\n          Best suited for developers seeking efficient scaling with minimal delays in transaction finality.\n          <br />\n          <i>Est time: 1h</i>\n\n          <br /><br />\n          <h2>Bitcoin Layer 3 (L3): </h2>\n          <h3>ZK Rollup: </h3>\n          Aggregates transactions off-chain and submits a single proof to Bitcoin, greatly improving scalability and\n          reducing fees. Ideal for developers needing high transaction throughput with strong security guarantees.\n          <br />\n          <i>Est time: 90m</i>",
      options: [
        {
          key: 'layer1',
          title: 'Metaprotocol',
          value: 20,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 2871,
          priceBVM: 6810,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: [],
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-l1-v2.svg',
          logo: '',
          setupLogo: '',
          needContactUs: true,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: {
            type: 'text',
            attrs: {
              api_check_valid:
                'https://raas.bvm.network/api/validate-chain-info/layer1_name',
              defaut_value: '',
              name: 'layer1_name',
              placeholder: '',
              required: 'true',
              value: '',
            },
          },
          deployTime: '48h',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'layer2',
          title: 'ZK Rollup',
          value: 21,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 1371,
          priceBVM: 3250,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: [],
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-l2.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '5h',
          deployTimeTestnet: '1h',
          order: 0,
        },
        {
          key: 'layer2_hybrid',
          title: 'ZK Rollup Hybrid',
          value: 21,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 1071,
          priceBVM: 2540,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: [],
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-l2.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '5h',
          deployTimeTestnet: '1h',
          order: 0,
        },
        {
          key: 'layer3',
          title: 'Bitcoin L3 with ZK Rollup',
          value: 21,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 100,
          priceBVM: 240,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-l2.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'layer2_op',
          title: 'Optimistic Rollup Hybrid',
          value: 20,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 1971,
          priceBVM: 4675,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: [],
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-l2.svg',
          logo: '',
          setupLogo: '',
          needContactUs: true,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '5h',
          deployTimeTestnet: '1h',
          order: 0,
        },
      ],
      color: '#368cdc',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 0,
    },
    {
      id: '66bb30a7ab0ec87655a8e094',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'tools',
      title: 'Tools',
      required: false,
      tooltip: '',
      options: [
        {
          key: 'explorer',
          title: 'Explorer',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-explorer.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/account_abstraction_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_account_abstraction_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: true,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
        {
          key: 'lightnode',
          title: 'Light Node',
          value: 1,
          valueStr: '',
          selectable: true,
          hidden: true,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: [],
          supportLayer: '',
          supportLayers: ['layer2'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-light.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          deployTime: '',
          deployTimeTestnet: '',
          order: 0,
        },
      ],
      color: '#db7d7d',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: true,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 7,
    },
  ],
};

export const MODEL_CATEGORY_MOCKUP: any = API_RESPONE.result;
