import { OrderItem, OrderStatus } from '@/stores/states/l2services/types';

export const ORDER_MOCKUP_DATA: any = {
  createAt: 1724403466,
  orderId: '66c84f0a5b66f48cfa744884',
  index: 169,
  registerTx: '',
  tcAddress: '0x4d0c64c6e576ad9206f87ac5e2d295043ba0ce8d',
  userName: '',
  serviceType: 21,
  serviceFee: '0',
  setupCost: '0',
  rollupCost: '',
  instanceId: '',
  reward: '',
  isWithdrawableReward: false,
  status: 0,
  monitorLink: '',
  minGasPrice: '',
  dataAvaibilityChain: 10,
  needToTopupBalance: '14135585744588015207',
  needToTopupBalanceUSD: '6.642256304e+18',
  nextBillingAt: 1729587466,
  plugins: [],
  dApps: [
    {
      orderID: '',
      userAddress: '',
      appID: 0,
      appURL: 'https://nakachain.xyz/wallet?chain=my-bitcoin-chain-7812',
      appCode: 'btc_bridge',
      appName: 'Bitcoin bridge',
      appDescription: '',
      appImageURL:
        'https://storage.googleapis.com/bvm-network/image/btc_bridge_ic.png',
      status: 'processing',
      statusJob: 0,
      priceUsd: 0,
      priceBvm: 0,
      aaPaymasterTokenID: '',
      aaTokenGas: '',
      aaPaymasterContract: '',
    },
    {
      orderID: '',
      userAddress: '',
      appID: 0,
      appURL: 'https://nakachain.xyz/wallet?chain=my-bitcoin-chain-7812',
      appCode: 'eth_bridge',
      appName: 'Ethereum bridge',
      appDescription: '',
      appImageURL:
        'https://storage.googleapis.com/bvm-network/image/eth_bridge_ic.png',
      status: 'done',
      statusJob: 0,
      priceUsd: 0,
      priceBvm: 0,
      aaPaymasterTokenID: '',
      aaTokenGas: '',
      aaPaymasterContract: '',
    },
  ],
  domain: 'my-bitcoin-chain-7812',
  chainId: '60679',
  chainName: 'My Bitcoin Chain  7812',
  description: '',
  finalizationPeriod: 86400,
  blockTime: 1,
  isMainnet: true,
  evMversion: 'zksync-evm',
  explorer: '',
  rpc: '',
  ws: '',
  l2BridgeContract: '',
  l2PortalContract: '',
  l2OracleContract: '',
  l2AddressManager: '',
  l2CrossDomainMessenger: '',
  preMint: 0,
  preMintAddress: '',
  preMintAmount: '',
  ticker: 'BVM',
  gasLimit: 0,
  bridgeStatus: 0,
  package: 0,
  packagePrice: 0,
  packagePriceUSD: 0,
  prover: 0,
  cpuCore: 8,
  memory: 16,
  storage: 320,
  thumb: '',
  logoURL: '',
  selectedOptions: [
    {
      id: '668f8ebf88f822fe3ebd3470',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'settlement',
      title: 'Base Chains',
      required: true,
      tooltip:
        'Select the base layer on which you want to build your blockchain. This will determine the base protocol and network characteristics, such as security, scalability, and consensus mechanisms.',
      options: [
        {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#F8B200',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Base Chain',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 0,
    },
    {
      id: '66ab4cb5ab0ec87655a8e084',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'layers',
      title: 'Scaling Solutions',
      required: true,
      tooltip:
        "<h2>Bitcoin Layer 1 (L1):</h2>\n          <h3>EVM Metaprotocol: </h3>\n          Enables the deployment of EVM-compatible smart contracts while leveraging Bitcoin's security. Ideal for\n          developers familiar with Ethereum tools who seek the stability and security of Bitcoin.\n          <br />\n          <i>Est time: 48h</i>\n          <br /><br />\n          <h2>Bitcoin Layer 2 (L2): </h2>\n          <h3>ZK Rollup:</h3>\n          Implements Zero-Knowledge (ZK) technology on Bitcoin as the base layer to enhance scalability and transaction\n          efficiency. This option is perfect for developers focused on scaling while maintaining top-tier security on\n          Bitcoin’s L1.\n          <br />\n          <i>Est time: 1h</i>        \n         \n          <br /><br />\n          <h3>Optimistic Rollup:</h3>\n          Processes transactions off-chain under the assumption of validity, which lowers costs and boosts scalability.\n          Best suited for developers seeking efficient scaling with minimal delays in transaction finality.\n          <br />\n          <i>Est time: 1h</i>\n\n          <br /><br />\n          <h2>Bitcoin Layer 3 (L3): </h2>\n          <h3>ZK Rollup: </h3>\n          Aggregates transactions off-chain and submits a single proof to Bitcoin, greatly improving scalability and\n          reducing fees. Ideal for developers needing high transaction throughput with strong security guarantees.\n          <br />\n          <i>Est time: 90m</i>",
      options: [
        {
          key: 'layer3',
          title: 'Bitcoin L3 with ZK Rollup',
          value: 21,
          valueStr: '',
          selectable: true,
          hidden: true,
          priceUSD: 100,
          priceBVM: 215,
          priceUSDTestnet: 0,
          priceBVMTestnet: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-l2.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#368cdc',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 0,
    },
    {
      id: '668f8ebe88f822fe3ebd346e',
      created_at: '2024-07-11T07:50:22.365Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'network',
      title: 'Networks',
      required: true,
      tooltip:
        'Choose whether to test on the testnet for trials and development or deploy on the mainnet for production and live use.',
      options: [
        {
          key: 'mainnet',
          title: 'Mainnet',
          value: 1,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: '',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#FF7A41',
      type: 'module',
      disable: false,
      hidden: true,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 1,
    },
    {
      id: '668f8ebf88f822fe3ebd346f',
      created_at: '2024-07-11T07:50:23.442Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'hardware',
      title: 'Hardware',
      required: true,
      tooltip:
        'Select your hardware configuration to match the specific needs of your blockchain. Consider factors such as RAM, CPU cores, and storage capacity to ensure optimal performance and scalability.',
      options: [
        {
          key: '16g',
          title: '16 GB RAM, 8 cores, 320 GB SSD',
          value: 16785728,
          valueStr: '1',
          selectable: true,
          hidden: false,
          priceUSD: 99,
          priceBVM: 215,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#12DAC2',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 2,
    },
    {
      id: '668f8ebf88f822fe3ebd3472',
      created_at: '2024-07-11T07:50:23.774Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'storage',
      title: 'Data Availability',
      required: true,
      tooltip:
        'Ensure easy access to transaction details and smart contracts for all nodes on L1, L2, and even L3 networks. Using a separate DA layer reduces mainnet congestion, enhancing scalability, security, and transaction cost-efficiency.',
      options: [
        {
          key: 'polygon',
          title: 'Polygon',
          value: 10,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3', 'layer2'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-polygon.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#15C888',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'DA',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 4,
    },
    {
      id: '668f8ebf88f822fe3ebd3474',
      created_at: '2024-07-11T07:50:23.919Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'block_gas_limit',
      title: 'Gas',
      required: true,
      tooltip:
        'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
      options: [
        {
          key: '1m',
          title: '1,000,000,000',
          value: 1000000000,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: null,
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-min.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#FB9F00',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Block Gas Limit',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 5,
    },
    {
      id: '668f8ebf88f822fe3ebd3475',
      created_at: '2024-07-11T07:50:23.993Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'withdrawal_time',
      title: 'Withdrawals',
      required: true,
      tooltip:
        'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to the L1.',
      options: [
        {
          key: 'withdrawal_time_3',
          title: '24-hour',
          value: 86400,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3', 'layer2'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-slow.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#F200F2',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Withdrawal Time',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 6,
    },
    {
      id: '66bb30a7ab0ec87655a8e094',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'tools',
      title: 'Tools',
      required: false,
      tooltip: '',
      options: [
        {
          key: 'explorer',
          title: 'Explorer',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer1', 'layer3', 'layer2'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-explorer.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/account_abstraction_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_account_abstraction_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: true,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#db7d7d',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: true,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 7,
    },
    {
      id: '668f8ec088f822fe3ebd3477',
      created_at: '2024-07-11T07:50:24.179Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'bridge_apps',
      title: 'Bridges',
      required: false,
      tooltip:
        'Bring BTC, ETH, SOL, BNB and other assets to your blockchain and transfer them back to Bitcoin and Ethereum networks.',
      options: [
        {
          key: 'btc_bridge',
          title: 'Bitcoin',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'mainnet',
          requiredFor: null,
          supportLayer: 'layer3',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/btc_bridge_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
        {
          key: 'eth_bridge',
          title: 'Ethereum',
          value: 1,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'mainnet',
          requiredFor: null,
          supportLayer: 'layer3',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/eth_bridge_ic.png',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#855AFF',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: true,
      confuseWord: true,
      confuseIcon:
        'https://storage.googleapis.com/bvm-network/icons-tool/icon-bridge-confused.svg',
      confuseTitle: 'Your chain',
      updatable: true,
      whitelistAddress: null,
      isChain: false,
      order: 9,
    },
    {
      id: '668f8ec088f822fe3ebd3476',
      created_at: '2024-07-11T07:50:24.072Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'wallet',
      title: 'UX',
      required: false,
      tooltip:
        'This module enhances user experience by allowing gas fees to be paid in different cryptocurrencies, eliminating the need to hold a specific one for transaction fees.',
      options: [
        {
          key: 'account_abstraction',
          title: 'Account Abstraction',
          value: 0,
          valueStr: '',
          selectable: true,
          hidden: false,
          priceUSD: 0,
          priceBVM: 0,
          priceUSDTestnet: null,
          priceBVMTestnet: null,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-wallet.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/account_abstraction_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_account_abstraction_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: true,
          appTemplateUrl: '',
          addOnInputs: null,
          order: 0,
        },
      ],
      color: '#00C1CD',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: true,
      whitelistAddress: [
        '0x4d0c64c6e576ad9206f87ac5e2d295043ba0ce8d',
        '0x63f674814Ab1329f05D2B9237Bc03C9c87ded2Aa',
        '0x4113ed747047863Ea729f30C1164328D9Cc8CfcF',
      ],
      isChain: false,
      order: 8,
    },
  ],
};
