import { OrderItem, OrderStatus } from '@/stores/states/l2services/types';

export const ORDER_MOCKUP_DATA: OrderItem = {
  orderId: '66c2f761a760de9c1d9b5426',

  rewardFormatted: '',
  setupCostFormatted: '',
  needToTopupBalanceFormatted: '',
  isNeedTopup: true,
  serviceFeeFormatted: '',
  rollupCostFormatted: '',
  isOwner: true,

  index: 165,
  tcAddress: '0x4d0c64c6e576ad9206f87ac5e2d295043ba0ce8d',
  userName: '',
  serviceType: 21,
  serviceFee: '0',
  setupCost: '0',
  rollupCost: '',
  instanceId: '',
  reward: '',
  isWithdrawableReward: false,
  status: OrderStatus.Rejected, //Status Order
  monitorLink: '',
  minGasPrice: '',
  dataAvaibilityChain: 10,
  needToTopupBalance: '13380240150335337526',
  needToTopupBalanceUSD: '6.591645758e+18',
  plugins: [],
  dApps: [
    {
      orderID: '66c2f761a760de9c1d9b5426',
      userAddress: '0x4d0c64c6e576ad9206f87ac5e2d295043ba0ce8d',
      appID: 0,
      appURL: '',
      appCode: 'account_abstraction',
      appName: 'account_abstraction',
      appDescription: '',
      appImageURL: '',
      status: 'done',
      statusJob: 0,
      priceUsd: 0,
      priceBvm: 0,
      aaPaymasterTokenID: '0xa6e814e66ee6a8ebb162c168989fdc495ce29017',
      aaTokenGas: '500000000000000000',
      aaPaymasterContract: '',
    },
  ],
  domain: 'my-bitcoin-rollup-bvm-9818',
  chainId: '90908',
  chainName: 'My Bitcoin Chain 9818',
  description: '',
  finalizationPeriod: 86400,
  blockTime: '1',
  isMainnet: true,
  explorer: '',
  rpc: '',
  l2BridgeContract: '',
  l2PortalContract: '',
  preMint: 0,
  preMintAddress: '',
  ticker: 'BVM',
  gasLimit: 0,
  bridgeStatus: 0,
  package: 0,
  packagePrice: 0,
  packagePriceUSD: 0,
  prover: 0,
  cpuCore: 8,
  memory: 16,
  storage: 320,
  thumb: '',
  logoURL: '',
  selectedOptions: [
    {
      id: '668f8ebf88f822fe3ebd3470',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'settlement',
      title: 'Layer 1',
      required: true,
      tooltip:
        'Select the base layer on which you want to build your blockchain. This will determine the base protocol and network characteristics, such as security, scalability, and consensus mechanisms.',
      options: [
        {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 0,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#F8B200',
      type: 'module',
      disable: false,
      hidden: true,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Base Layer',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 0,
    },
    {
      id: '66ab4cb5ab0ec87655a8e084',
      created_at: '2024-07-11T07:50:23.589Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'layers',
      title: 'Layers',
      required: true,
      tooltip:
        'To improve performance and satisfy the demands of your users, select the layer that best matches with the aims of your project.',
      options: [
        {
          key: 'layer3',
          title: 'Bitcoin L3',
          value: 0,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip:
            'For advanced use cases, offering maximum flexibility and scalability for developing sophisticated dApps and appchains.',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-l3.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#368cdc',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 0,
    },
    {
      id: '668f8ebe88f822fe3ebd346e',
      created_at: '2024-07-11T07:50:22.365Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'network',
      title: 'Networks',
      required: true,
      tooltip:
        'Choose whether to test on the testnet for trials and development or deploy on the mainnet for production and live use.',
      options: [
        {
          key: 'mainnet',
          title: 'Mainnet',
          value: 1,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: '',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#FF7A41',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 1,
    },
    {
      id: '668f8ebf88f822fe3ebd346f',
      created_at: '2024-07-11T07:50:23.442Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'hardware',
      title: 'Hardware',
      required: true,
      tooltip:
        'Select your hardware configuration to match the specific needs of your blockchain. Consider factors such as RAM, CPU cores, and storage capacity to ensure optimal performance and scalability.',
      options: [
        {
          key: '16g',
          title: '16 GB RAM, 8 cores, 320 GB SSD',
          value: 16785728,
          valueStr: '1',
          selectable: true,
          priceUSD: 99,
          priceBVM: 205,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#12DAC2',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 2,
    },
    {
      id: '668f8ebf88f822fe3ebd3471',
      created_at: '2024-07-11T07:50:23.694Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'compute',
      title: 'Rollups',
      required: true,
      tooltip:
        'Choose the scaling solution tailored to your needs. Rollups enhance scalability and reduce transaction costs by processing transactions off-chain while posting transaction data on-chain.',
      options: [
        {
          key: 'zk',
          title: 'ZK Rollup',
          value: 21,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip:
            'Offer even higher scalability and cost-efficiency by bundling many transactions into a single proof. Provide strong security through zero-knowledge proofs, enabling fast finality and enhanced privacy. Can be done automatically.',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer2', 'layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#A041FF',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: false,
      confuseIcon: '',
      confuseTitle: '',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 3,
    },
    {
      id: '668f8ebf88f822fe3ebd3472',
      created_at: '2024-07-11T07:50:23.774Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'storage',
      title: 'Data Availability',
      required: true,
      tooltip:
        'Ensure easy access to transaction details and smart contracts for all nodes on L1, L2, and even L3 networks. Using a separate DA layer reduces mainnet congestion, enhancing scalability, security, and transaction cost-efficiency.',
      options: [
        {
          key: 'polygon',
          title: 'Polygon',
          value: 10,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3', 'layer2'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-polygon.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#15C888',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'DA',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 4,
    },
    {
      id: '668f8ebf88f822fe3ebd3474',
      created_at: '2024-07-11T07:50:23.919Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'block_gas_limit',
      title: 'Gas',
      required: true,
      tooltip:
        'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
      options: [
        {
          key: '1m',
          title: '1,000,000,000',
          value: 1000000000,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-min.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#FB9F00',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Block Gas Limit',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 5,
    },
    {
      id: '668f8ebf88f822fe3ebd3475',
      created_at: '2024-07-11T07:50:23.993Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'withdrawal_time',
      title: 'Withdrawals',
      required: true,
      tooltip:
        'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to the L1.',
      options: [
        {
          key: 'withdrawal_time_3',
          title: '24-hour',
          value: 86400,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3', 'layer2'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-slow.svg',
          logo: '',
          setupLogo: '',
          needContactUs: false,
          needConfig: false,
          needInstall: false,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#F200F2',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: 'Withdrawal Time',
      updatable: false,
      whitelistAddress: null,
      isChain: true,
      order: 6,
    },
    {
      id: '668f8ec088f822fe3ebd3476',
      created_at: '2024-07-11T07:50:24.072Z',
      updated_at: '0001-01-01T00:00:00Z',
      key: 'wallet',
      title: 'UX',
      required: false,
      tooltip:
        'This module enhances user experience by allowing gas fees to be paid in different cryptocurrencies, eliminating the need to hold a specific one for transaction fees.',
      options: [
        {
          key: 'account_abstraction',
          title: 'Account Abstraction',
          value: 0,
          valueStr: '',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          requiredFor: null,
          supportLayer: '',
          supportLayers: ['layer3'],
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-wallet.svg',
          logo: 'https://storage.googleapis.com/bvm-network/image/account_abstraction_ic.png',
          setupLogo:
            'https://storage.googleapis.com/bvm-network/image/app_account_abstraction_ic.png',
          needContactUs: false,
          needConfig: true,
          needInstall: true,
          appTemplateUrl: '',
          order: 0,
        },
      ],
      color: '#00C1CD',
      type: 'module',
      disable: false,
      hidden: false,
      multiChoice: false,
      confuseWord: true,
      confuseIcon: '',
      confuseTitle: '',
      updatable: true,
      whitelistAddress: [
        '0x4d0c64c6e576ad9206f87ac5e2d295043ba0ce8d',
        '0x63f674814Ab1329f05D2B9237Bc03C9c87ded2Aa',
        '0x4113ed747047863Ea729f30C1164328D9Cc8CfcF',
      ],
      isChain: false,
      order: 8,
    },
  ],
  createAt: '',
  evmVersion: '',
  nextBillingAt: '',
  isConstant: false,
};
