export const APPS = [
  {
    id: 1,
    title: 'Create Token',
    key: 'create_token',
    tooltip: "Create token",
    color: "#FF7A41",
    settings: [
      {
        "id": "668f8ebe88f822fe3ebd346e",
        "created_at": "2024-07-11T07:50:22.365Z",
        "updated_at": "0001-01-01T00:00:00Z",
        "key": "information",
        "title": "Information",
        "required": true,
        "tooltip": "Information",
        "options": [
          {
            "key": "token_name",
            "title": "Token Name",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
          {
            "key": "symbol",
            "title": "Symbol",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
          {
            "key": "supply",
            "title": "Total Supply",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
        ],
        "color": "#FF7A41",
        "type": "module",
        "disable": false,
        "multiChoice": false,
        "confuseWord": false,
        "confuseIcon": "",
        "confuseTitle": "",
        "whitelistAddress": null,
        "order": 1
      },
      {
        "id": "668f8ebe88f822fe3ebd346e",
        "created_at": "2024-07-11T07:50:22.365Z",
        "updated_at": "0001-01-01T00:00:00Z",
        "key": "tokenomics",
        "title": "Tokenomics",
        "required": true,
        "tooltip": "Tokenomics",
        "options": [
          {
            "key": "name",
            "title": "Name",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
          {
            "key": "amount",
            "title": "Amount",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
          {
            "key": "receiver_address",
            "title": "Receiver Addresss",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
        ],
        color: "#12DAC2",
        "type": "module",
        "disable": false,
        "multiChoice": false,
        "confuseWord": false,
        "confuseIcon": "",
        "confuseTitle": "",
        "whitelistAddress": null,
        "order": 1
      },
    ]
  },
  {
    id: 2,
    title: 'Staking',
    key: 'staking',
    tooltip: "Staking",
    color: "#12DAC2",
    settings: [
      {
        "id": "668f8ebe88f822fe3ebd346e",
        "created_at": "2024-07-11T07:50:22.365Z",
        "updated_at": "0001-01-01T00:00:00Z",
        "key": "information",
        "title": "Information",
        "required": true,
        "tooltip": "Information",
        "options": [
          {
            "key": "token_name",
            "title": "Token Name",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
          {
            "key": "symbol",
            "title": "Symbol",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
          {
            "key": "supply",
            "title": "Total Supply",
            "value": 1,
            "valueStr": "",
            "selectable": true,
            "priceUSD": 0,
            "priceBVM": 0,
            "tooltip": "",
            "supportNetwork": "",
            "icon": "https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg",
            "logo": "",
            "needContactUs": false,
            "order": 0
          },
        ],
        "color": "#FF7A41",
        "type": "module",
        "disable": false,
        "multiChoice": false,
        "confuseWord": false,
        "confuseIcon": "",
        "confuseTitle": "",
        "whitelistAddress": null,
        "order": 1
      },
    ]
  },
]
