import {
  PRICING_PACKGE,
  PRICING_PACKGE_MAP,
} from '@/modules/PricingV2/constants';

export const FAKE_DATA_PACKAGE = [
  {
    id: '0',
    color: 'GREEN',
    template: PRICING_PACKGE_MAP[PRICING_PACKGE.Hacker],
    link: `/rollups/customizev2?package=${PRICING_PACKGE.Hacker}`,
    content: 'The easiest way to launch your blockchain',
    price: '$99',
    check: true,
    options: [
      '16 GB RAM',
      '8 cores',
      '320 GB SSD',
      '320 GB SSD',
      '320 GB SSD',
      '320 GB SSD',
      '320 GB SSD',
    ],
    data: [
      {
        id: '668f8ebe88f822fe3ebd346e',
        created_at: '2024-07-11T07:50:22.365Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'network',
        title: 'Network',
        required: true,
        tooltip:
          'Select whether you want to create a testnet or deploy a mainnet.',
        color: '#FF7A41',
        type: 'module',
        disable: false,
        value: {
          key: 'mainnet',
          title: 'Mainnet',
          value: 'mainnet',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: '',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
          label: 'Mainnet',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd346f',
        created_at: '2024-07-11T07:50:23.442Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'hardware',
        title: 'Hardware',
        required: true,
        tooltip: '',
        color: '#12DAC2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '16g',
          title: '16 GB RAM, 8 cores, 320 GB SSD',
          value: '16g',
          selectable: true,
          priceUSD: 99,
          priceBVM: 160.78928324848457,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '16 GB RAM, 8 cores, 320 GB SSD',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3470',
        created_at: '2024-07-11T07:50:23.589Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'settlement',
        title: 'Settlement',
        required: false,
        tooltip: '',
        color: '#F8B200',
        type: 'module',
        disable: false,
        value: {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 'bitcoin',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          label: 'Bitcoin',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3471',
        created_at: '2024-07-11T07:50:23.694Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'compute',
        title: 'Compute',
        required: false,
        tooltip: '',
        color: '#A041FF',
        type: 'module',
        disable: false,
        value: {
          key: 'zk',
          title: 'Zk Rollups',
          value: 'zk',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
          label: 'Zk Rollups',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3472',
        created_at: '2024-07-11T07:50:23.774Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'storage',
        title: 'Storage',
        required: false,
        tooltip:
          'The data of your blockchain is written to a Data Availability layer such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.',
        color: '#15C888',
        type: 'module',
        disable: false,
        value: null,
      },
      {
        id: '668f8ebf88f822fe3ebd3473',
        created_at: '2024-07-11T07:50:23.844Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'zk_prover',
        title: 'ZK Prover',
        required: false,
        tooltip: '',
        color: '#15BDC8',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ebf88f822fe3ebd3474',
        created_at: '2024-07-11T07:50:23.919Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'block_gas_limit',
        title: 'Block Gas Limit',
        required: false,
        tooltip:
          'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
        color: '#FB9F00',
        type: 'dropdown',
        disable: false,
        value: {
          key: '1m',
          title: '1,000,000,000',
          value: '1m',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '1,000,000,000',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3475',
        created_at: '2024-07-11T07:50:23.993Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'withdrawal_time',
        title: 'Withdrawal time',
        required: false,
        tooltip:
          'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to Supersonic. This duration primarily depends on the time required for the prover to submit a zk-proof to the verifier contracts deployed on Supersonic.',
        color: '#F200F2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '2h',
          title: '2 hours',
          value: '2h',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '2 hours',
          disabled: false,
        },
      },
      {
        id: '668f8ec088f822fe3ebd3476',
        created_at: '2024-07-11T07:50:24.072Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'wallet',
        title: 'Wallet',
        required: false,
        tooltip: '',
        color: '#00C1CD',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd3477',
        created_at: '2024-07-11T07:50:24.179Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'bridge_apps',
        title: 'Bridge Apps',
        required: false,
        tooltip: '',
        color: '#6B39F9',
        type: 'module',
        disable: false,
        value: {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 'bitcoin',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'mainnet',
          icon: '',
          label: 'Bitcoin',
          disabled: false,
        },
      },
      {
        id: '668f8ec088f822fe3ebd3478',
        created_at: '2024-07-11T07:50:24.299Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'defi_apps',
        title: 'DeFi Apps',
        required: false,
        tooltip: '',
        color: '#F76649',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd3479',
        created_at: '2024-07-11T07:50:24.462Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'degen_apps',
        title: 'Degen Apps',
        required: false,
        tooltip: '',
        color: '#E6004D',
        type: 'module',
        disable: false,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd347a',
        created_at: '2024-07-11T07:50:24.535Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'gaming_apps',
        title: 'Gaming Apps',
        required: false,
        tooltip: '',
        color: '#C000E6',
        type: 'module',
        disable: false,
        value: null,
      },
    ],
  },
  {
    id: '1',
    color: 'BLUE',
    template: PRICING_PACKGE_MAP[PRICING_PACKGE.Growth],
    link: `/rollups/customizev2?package=${PRICING_PACKGE.Growth}`,
    content: 'Scale your blockchain as you go',
    price: '$699',
    check: false,
    options: [
      '32 GB RAM',
      '16 cores',
      '400 GB SSD',
      '400 GB SSD',
      '400 GB SSD',
      '400 GB SSD',
    ],
    data: [
      {
        id: '668f8ebe88f822fe3ebd346e',
        created_at: '2024-07-11T07:50:22.365Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'network',
        title: 'Network',
        required: true,
        tooltip:
          'Select whether you want to create a testnet or deploy a mainnet.',
        color: '#FF7A41',
        type: 'module',
        disable: false,
        value: {
          key: 'mainnet',
          title: 'Mainnet',
          value: 'mainnet',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: '',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
          label: 'Mainnet',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd346f',
        created_at: '2024-07-11T07:50:23.442Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'hardware',
        title: 'Hardware',
        required: true,
        tooltip: '',
        color: '#12DAC2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '32g',
          title: '32 GB RAM, 16 cores, 400 GB SSD',
          value: '32g',
          selectable: true,
          priceUSD: 499,
          priceBVM: 810.4429529393313,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '32 GB RAM, 16 cores, 400 GB SSD',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3470',
        created_at: '2024-07-11T07:50:23.589Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'settlement',
        title: 'Settlement',
        required: false,
        tooltip: '',
        color: '#F8B200',
        type: 'module',
        disable: false,
        value: {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 'bitcoin',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          label: 'Bitcoin',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3471',
        created_at: '2024-07-11T07:50:23.694Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'compute',
        title: 'Compute',
        required: false,
        tooltip: '',
        color: '#A041FF',
        type: 'module',
        disable: false,
        value: {
          key: 'zk',
          title: 'Zk Rollups',
          value: 'zk',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
          label: 'Zk Rollups',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3472',
        created_at: '2024-07-11T07:50:23.774Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'storage',
        title: 'Storage',
        required: false,
        tooltip:
          'The data of your blockchain is written to a Data Availability layer such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.',
        color: '#15C888',
        type: 'module',
        disable: false,
        value: null,
      },
      {
        id: '668f8ebf88f822fe3ebd3473',
        created_at: '2024-07-11T07:50:23.844Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'zk_prover',
        title: 'ZK Prover',
        required: false,
        tooltip: '',
        color: '#15BDC8',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ebf88f822fe3ebd3474',
        created_at: '2024-07-11T07:50:23.919Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'block_gas_limit',
        title: 'Block Gas Limit',
        required: false,
        tooltip:
          'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
        color: '#FB9F00',
        type: 'dropdown',
        disable: false,
        value: {
          key: '2m',
          title: '2,000,000,000',
          value: '2m',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '2,000,000,000',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3475',
        created_at: '2024-07-11T07:50:23.993Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'withdrawal_time',
        title: 'Withdrawal time',
        required: false,
        tooltip:
          'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to Supersonic. This duration primarily depends on the time required for the prover to submit a zk-proof to the verifier contracts deployed on Supersonic.',
        color: '#F200F2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '4h',
          title: '4 hours',
          value: '4h',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '4 hours',
          disabled: false,
        },
      },
      {
        id: '668f8ec088f822fe3ebd3476',
        created_at: '2024-07-11T07:50:24.072Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'wallet',
        title: 'Wallet',
        required: false,
        tooltip: '',
        color: '#00C1CD',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd3477',
        created_at: '2024-07-11T07:50:24.179Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'bridge_apps',
        title: 'Bridge Apps',
        required: false,
        tooltip: '',
        color: '#6B39F9',
        type: 'module',
        disable: false,
        value: {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 'bitcoin',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'mainnet',
          icon: '',
          label: 'Bitcoin',
          disabled: false,
        },
      },
      {
        id: '668f8ec088f822fe3ebd3478',
        created_at: '2024-07-11T07:50:24.299Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'defi_apps',
        title: 'DeFi Apps',
        required: false,
        tooltip: '',
        color: '#F76649',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd3479',
        created_at: '2024-07-11T07:50:24.462Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'degen_apps',
        title: 'Degen Apps',
        required: false,
        tooltip: '',
        color: '#E6004D',
        type: 'module',
        disable: false,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd347a',
        created_at: '2024-07-11T07:50:24.535Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'gaming_apps',
        title: 'Gaming Apps',
        required: false,
        tooltip: '',
        color: '#C000E6',
        type: 'module',
        disable: false,
        value: null,
      },
    ],
  },
  {
    id: '2',
    color: 'ORANGE',
    template: PRICING_PACKGE_MAP[PRICING_PACKGE.Secure],
    link: `/rollups/customizev2?package=${PRICING_PACKGE.Secure}`,
    content: 'Fully secure your blockchain with a cryptographic prover',
    check: false,
    price: '$1999',
    options: ['64 GB RAM', '32 cores', '650 GB SSD', '650 GB SSD'],
    data: [
      {
        id: '668f8ebe88f822fe3ebd346e',
        created_at: '2024-07-11T07:50:22.365Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'network',
        title: 'Network',
        required: true,
        tooltip:
          'Select whether you want to create a testnet or deploy a mainnet.',
        color: '#FF7A41',
        type: 'module',
        disable: false,
        value: {
          key: 'mainnet',
          title: 'Mainnet',
          value: 'mainnet',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: '',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
          label: 'Mainnet',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd346f',
        created_at: '2024-07-11T07:50:23.442Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'hardware',
        title: 'Hardware',
        required: true,
        tooltip: '',
        color: '#12DAC2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '64g',
          title: '64 GB RAM, 32 cores, 650 GB SSD',
          value: '64g',
          selectable: true,
          priceUSD: 699,
          priceBVM: 1135.2697877847547,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '64 GB RAM, 32 cores, 650 GB SSD',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3470',
        created_at: '2024-07-11T07:50:23.589Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'settlement',
        title: 'Settlement',
        required: false,
        tooltip: '',
        color: '#F8B200',
        type: 'module',
        disable: false,
        value: {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 'bitcoin',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
          label: 'Bitcoin',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3471',
        created_at: '2024-07-11T07:50:23.694Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'compute',
        title: 'Compute',
        required: false,
        tooltip: '',
        color: '#A041FF',
        type: 'module',
        disable: false,
        value: {
          key: 'zk',
          title: 'Zk Rollups',
          value: 'zk',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
          label: 'Zk Rollups',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3472',
        created_at: '2024-07-11T07:50:23.774Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'storage',
        title: 'Storage',
        required: false,
        tooltip:
          'The data of your blockchain is written to a Data Availability layer such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.',
        color: '#15C888',
        type: 'module',
        disable: false,
        value: null,
      },
      {
        id: '668f8ebf88f822fe3ebd3473',
        created_at: '2024-07-11T07:50:23.844Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'zk_prover',
        title: 'ZK Prover',
        required: false,
        tooltip: '',
        color: '#15BDC8',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ebf88f822fe3ebd3474',
        created_at: '2024-07-11T07:50:23.919Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'block_gas_limit',
        title: 'Block Gas Limit',
        required: false,
        tooltip:
          'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
        color: '#FB9F00',
        type: 'dropdown',
        disable: false,
        value: {
          key: '4m',
          title: '4,000,000,000',
          value: '4m',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '4,000,000,000',
          disabled: false,
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3475',
        created_at: '2024-07-11T07:50:23.993Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'withdrawal_time',
        title: 'Withdrawal time',
        required: false,
        tooltip:
          'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to Supersonic. This duration primarily depends on the time required for the prover to submit a zk-proof to the verifier contracts deployed on Supersonic.',
        color: '#F200F2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '2h',
          title: '2 hours',
          value: '2h',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
          label: '2 hours',
          disabled: false,
        },
      },
      {
        id: '668f8ec088f822fe3ebd3476',
        created_at: '2024-07-11T07:50:24.072Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'wallet',
        title: 'Wallet',
        required: false,
        tooltip: '',
        color: '#00C1CD',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd3477',
        created_at: '2024-07-11T07:50:24.179Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'bridge_apps',
        title: 'Bridge Apps',
        required: false,
        tooltip: '',
        color: '#6B39F9',
        type: 'module',
        disable: false,
        value: {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 'bitcoin',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'mainnet',
          icon: '',
          label: 'Bitcoin',
          disabled: false,
        },
      },
      {
        id: '668f8ec088f822fe3ebd3478',
        created_at: '2024-07-11T07:50:24.299Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'defi_apps',
        title: 'DeFi Apps',
        required: false,
        tooltip: '',
        color: '#F76649',
        type: 'module',
        disable: true,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd3479',
        created_at: '2024-07-11T07:50:24.462Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'degen_apps',
        title: 'Degen Apps',
        required: false,
        tooltip: '',
        color: '#E6004D',
        type: 'module',
        disable: false,
        value: null,
      },
      {
        id: '668f8ec088f822fe3ebd347a',
        created_at: '2024-07-11T07:50:24.535Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'gaming_apps',
        title: 'Gaming Apps',
        required: false,
        tooltip: '',
        color: '#C000E6',
        type: 'module',
        disable: false,
        value: null,
      },
    ],
  },
];
