import React from 'react';
import { DALayerEnum, NetworkEnum } from './Buy.constanst';
import { ORDER_FIELD } from './stores';
import { LegoColor } from './components3/BoxOptionV2';

export type OrderFormOption = {
  [key in (typeof ORDER_FIELD)[keyof typeof ORDER_FIELD]]: {
    title: string;
    subTitle: string;
    background: LegoColor;
    backgroundParent?: LegoColor;
    isRequired?: boolean;
    description?: {
      title: string;
      content: JSX.Element;
    };
    options?: {
      id: number;
      label: string;
      keyInField?: string;
      value: NetworkEnum | DALayerEnum | number;
      icon?: string;
      isDisabled?: boolean;
      avalaibleNetworks?: NetworkEnum[];
    }[];
  };
};

export const OrderFormOptions: OrderFormOption = {
  [ORDER_FIELD.CHAIN_NAME]: {
    title: 'Chain Name',
    subTitle: 'Chain Name',
    background: 'brown',
  },
  [ORDER_FIELD.NETWORK]: {
    title: 'Network',
    subTitle: 'Network',
    background: 'brown',
    isRequired: true,
    description: {
      title: 'Network',
      content: (
        <p>Select whether you want to create a testnet or deploy a mainnet.</p>
      ),
    },
    options: [
      {
        id: 1,
        label: 'Mainnet',
        value: NetworkEnum.Network_Mainnet,
        icon: '/landingV3/images/pricing/7.png',
      },
      {
        id: 2,
        label: 'Testnet',
        value: NetworkEnum.Network_Testnet,
        icon: '/landingV3/images/pricing/8.png',
      },
    ],
  },
  [ORDER_FIELD.DATA_AVAILABILITY_CHAIN]: {
    title: ' Data Availability',
    subTitle: 'Data Availability',
    background: 'violet',
    description: {
      title: 'Data Availability',
      content: (
        <p>
          The data of your blockchain is written to a Data Availability layer
          such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
        </p>
      ),
    },
    options: [
      {
        id: 1,
        label: 'Polygon',
        value: DALayerEnum.DALayer_PLG,
        icon: '/landingV3/images/pricing/1.png',
        avalaibleNetworks: [
          NetworkEnum.Network_Mainnet,
          NetworkEnum.Network_Testnet,
        ],
      },
      {
        id: 6,
        label: 'Avail',
        isDisabled: true,
        value: DALayerEnum.DALayer_AVAIL,
        avalaibleNetworks: [NetworkEnum.Network_Testnet],
        icon: '/landingV3/images/pricing/6.png',
      },
      {
        id: 2,
        label: 'Celestia',
        value: DALayerEnum.DALayer_Celestia,
        isDisabled: true,
        avalaibleNetworks: [],
        icon: '/landingV3/images/pricing/2.png',
      },
      {
        id: 3,
        label: 'NearDA',
        value: DALayerEnum.DALayer_NearDa,
        isDisabled: true,
        avalaibleNetworks: [],
        icon: '/landingV3/images/pricing/3.png',
      },
      {
        id: 4,
        label: 'Eigen',
        value: DALayerEnum.DALayer_Eigen,
        icon: '/landingV3/images/pricing/4.png',
        avalaibleNetworks: [],
        isDisabled: true,
      },
      {
        id: 5,
        label: 'Filecoin',
        value: DALayerEnum.DALayer_FILECOIN,
        icon: '/landingV3/images/pricing/5.png',
        avalaibleNetworks: [],

        isDisabled: true,
      },
    ],
  },
  [ORDER_FIELD.GAS_LIMIT]: {
    title: ' Block Gas Limit',
    subTitle: 'Block Gas Limit',
    background: 'green',
    description: {
      title: 'Block Gas Limit',
      content: (
        <p>
          The block gas limit defines the maximum amount of gas that all
          transactions in a single block can consume.
        </p>
      ),
    },
  },
  [ORDER_FIELD.WITHDRAW_PERIOD]: {
    title: 'Withdrawal Time',
    subTitle: 'Withdrawal Time',
    background: 'pink',
    description: {
      title: 'Withdrawal Time',
      content: (
        <p>
          The withdrawal period is the time frame during which your users can
          withdraw their funds from your blockchain.
        </p>
      ),
    },
  },
  // [ORDER_FIELD.DEFI]: {
  //   title: 'DeFi',
  //   subTitle: 'DeFi',
  //   background: 'brown',
  //   backgroundParent: 'orange',
  //   options: [
  //     {
  //       label: 'Issue a token',
  //       keyInField: 'nestedKey1',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/13.png',
  //       id: 1,
  //     },
  //     {
  //       label: 'Orderbook',
  //       keyInField: 'nestedKey2',
  //       value: 2,
  //       icon: '/landingV3/images/pricing/12.png',
  //       id: 2,
  //     },
  //     {
  //       label: 'Orderbook',
  //       keyInField: 'nestedKey1',
  //       value: 3,
  //       icon: '/landingV3/images/pricing/14.png',
  //       id: 3,
  //     },
  //   ],
  //   description: {
  //     title: 'DeFi',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  // },
  // [ORDER_FIELD.BRIDGEAPPS]: {
  //   title: 'Bridge Apps',
  //   subTitle: 'Bridge Apps',
  //   background: 'blue',
  //   description: {
  //     title: 'Bridge Apps',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  //   options: [
  //     {
  //       label: 'Bridge',
  //       id: 1,
  //       value: 1,
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'Bitcoin Bridge',
  //       id: 2,
  //       value: 2,
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'Ethereum Bridge',
  //       id: 3,
  //       value: 3,
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'Solana Bridge',
  //       id: 4,
  //       value: 4,
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'BRC-20 Bridge',
  //       id: 5,
  //       value: 5,
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'Runes Bridge',
  //       id: 6,
  //       value: 6,
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'Ordinals Bridge',
  //       id: 7,
  //       value: 7,
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'Decentralized Bridge for Bitcoin',
  //       id: 8,
  //       value: 8,
  //       avalaibleNetworks: [],
  //     },
  //   ],
  // },
  // [ORDER_FIELD.COMPUTED]: {
  //   title: 'Compute',
  //   subTitle: 'Compute',
  //   background: 'violet',
  //   options: [
  //     {
  //       label: 'ZK Rollups',
  //       id: 1,
  //       value: 1,
  //       icon: '/landingV3/images/pricing/10.png',
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'Optimistic Rollups',
  //       id: 2,
  //       value: 2,
  //       icon: '/landingV3/images/pricing/9.png',
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       label: 'GPU Rollups',
  //       id: 3,
  //       value: DALayerEnum.DALayer_PLG,
  //       avalaibleNetworks: [],
  //     },
  //   ],
  //   description: {
  //     title: 'Computed',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  // },
  // [ORDER_FIELD.STORAGE]: {
  //   title: '8. Storage',
  //   subTitle: 'Storage',
  //   background: 'green',
  //   description: {
  //     title: 'Storage',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  //   options: [
  //     {
  //       id: 1,
  //       label: 'BVM DA',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/11.png',
  //       avalaibleNetworks: [
  //         NetworkEnum.Network_Mainnet,
  //         NetworkEnum.Network_Testnet,
  //       ],
  //     },
  //     {
  //       id: 6,
  //       label: 'Avail',
  //       value: DALayerEnum.DALayer_AVAIL,
  //       avalaibleNetworks: [],
  //       icon: '/landingV3/images/pricing/6.png',
  //     },
  //     {
  //       id: 2,
  //       label: 'Celestia',
  //       value: DALayerEnum.DALayer_Celestia,
  //       isDisabled: true,
  //       avalaibleNetworks: [NetworkEnum.Network_Testnet],
  //       icon: '/landingV3/images/pricing/2.png',
  //     },
  //     {
  //       id: 5,
  //       label: 'Filecoin',
  //       value: DALayerEnum.DALayer_FILECOIN,
  //       icon: '/landingV3/images/pricing/5.png',
  //       avalaibleNetworks: [],
  //       isDisabled: true,
  //     },
  //     {
  //       id: 3,
  //       label: 'NearDA',
  //       value: DALayerEnum.DALayer_NearDa,
  //       isDisabled: true,
  //       avalaibleNetworks: [],
  //       icon: '/landingV3/images/pricing/3.png',
  //     },
  //   ],
  // },

  // [ORDER_FIELD.SETTLEMENT]: {
  //   title: 'Settlement',
  //   subTitle: 'Settlement',
  //   background: 'yellow',
  //   options: [
  //     {
  //       id: 1,
  //       label: 'Bitcoin',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/15.png',
  //       avalaibleNetworks: [
  //         NetworkEnum.Network_Mainnet,
  //         NetworkEnum.Network_Testnet,
  //       ],
  //     },
  //     {
  //       id: 1,
  //       label: 'Ethereum',
  //       value: 2,
  //       icon: '/landingV3/images/pricing/16.png',
  //       avalaibleNetworks: [
  //         NetworkEnum.Network_Mainnet,
  //         NetworkEnum.Network_Testnet,
  //       ],
  //     },
  //   ],
  //   description: {
  //     title: 'Settlement',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  // },
  // [ORDER_FIELD.SYSTEMAPPS]: {
  //   title: 'System Apps',
  //   subTitle: 'System Apps',
  //   background: 'pink',
  //   options: [
  //     {
  //       id: 1,
  //       label: 'Explorer',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/17.png',
  //       avalaibleNetworks: [
  //         NetworkEnum.Network_Mainnet,
  //         NetworkEnum.Network_Testnet,
  //       ],
  //     },
  //   ],
  //   description: {
  //     title: 'System Apps',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  // },

  // [ORDER_FIELD.WALLET]: {
  //   title: 'Wallet',
  //   subTitle: 'Wallet',
  //   background: 'skyBlue',
  //   description: {
  //     title: 'Wallet',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  //   options: [
  //     {
  //       id: 1,
  //       label: 'Paymaster',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/18.png',
  //       avalaibleNetworks: [
  //         NetworkEnum.Network_Mainnet,
  //         NetworkEnum.Network_Testnet,
  //       ],
  //     },
  //   ],
  // },
  // [ORDER_FIELD.DEGENAPPS]: {
  //   title: 'Degen Apps',
  //   subTitle: 'Degen Apps',
  //   background: 'cowYellow',
  //   description: {
  //     title: 'Degen Apps',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  //   options: [
  //     {
  //       id: 1,
  //       label: 'NFT Raffle',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/19.png',
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       id: 1,
  //       label: 'NFT Raffle',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/20.png',
  //       avalaibleNetworks: [],
  //     },
  //     {
  //       id: 1,
  //       label: 'NFT Raffle',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/21.png',
  //       avalaibleNetworks: [],
  //     },
  //   ],
  // },

  // [ORDER_FIELD.GAMES]: {
  //   title: 'Games',
  //   subTitle: 'Games',
  //   background: 'green',
  //   description: {
  //     title: 'Games',
  //     content: (
  //       <p>
  //         The data of your blockchain is written to a Data Availability layer
  //         such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.
  //       </p>
  //     ),
  //   },
  //   options: [
  //     {
  //       id: 1,
  //       label: 'Games',
  //       value: 1,
  //       icon: '/landingV3/images/pricing/20.png',
  //       avalaibleNetworks: [],
  //     },
  //   ],
  // },
};

export const iconToolNames = [
  '/icons-tool/icon-avail.svg',
  '/icons-tool/icon-brc20.svg',
  '/icons-tool/icon-bridge-confused.svg',
  '/icons-tool/icon-btc-decen.svg',
  '/icons-tool/icon-btc.svg',
  '/icons-tool/icon-bull-bear.svg',
  '/icons-tool/icon-bvm.svg',
  '/icons-tool/icon-ceslestia.svg',
  '/icons-tool/icon-dex.svg',
  '/icons-tool/icon-eth.svg',
  '/icons-tool/icon-explorer.svg',
  '/icons-tool/icon-filecoin.svg',
  '/icons-tool/icon-game.svg',
  '/icons-tool/icon-gas-max.svg',
  '/icons-tool/icon-gas-medium.svg',
  '/icons-tool/icon-gas-min.svg',
  '/icons-tool/icon-hardware.svg',
  '/icons-tool/icon-issue-a-token.svg',
  '/icons-tool/icon-mainnet.svg',
  '/icons-tool/icon-near.svg',
  '/icons-tool/icon-op.svg',
  '/icons-tool/icon-orderbook.svg',
  '/icons-tool/icon-ordinals.svg',
  '/icons-tool/icon-perceptual.svg',
  '/icons-tool/icon-polygon.svg',
  '/icons-tool/icon-raffle.svg',
  '/icons-tool/icon-runes.svg',
  '/icons-tool/icon-solana.svg',
  '/icons-tool/icon-staking.svg',
  '/icons-tool/icon-testnet.svg',
  '/icons-tool/icon-time-fast.svg',
  '/icons-tool/icon-time-medium.svg',
  '/icons-tool/icon-time-slow.svg',
  '/icons-tool/icon-vesting.svg',
  '/icons-tool/icon-wallet.svg',
  '/icons-tool/icon-yolo.svg',
  '/icons-tool/icon-zk.svg',
];

export const mockupOptions: IModelCategory[] = [
  {
    id: '668f8ebe88f822fe3ebd346e',
    created_at: '2024-07-11T07:50:22.365Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'network',
    title: 'Network',
    required: true,
    tooltip:
      'Choose whether to test on the testnet for trials and development or deploy on the mainnet for production and live use.',
    options: [
      {
        key: 'mainnet',
        title: 'Mainnet',
        value: 1,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: '',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'testnet',
        title: 'Testnet',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: '',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-testnet.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#FF7A41',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 1,
  },
  {
    id: '668f8ebf88f822fe3ebd346f',
    created_at: '2024-07-11T07:50:23.442Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'hardware',
    title: 'Hardware',
    required: true,
    tooltip:
      'Select your hardware configuration to match the specific needs of your blockchain. Consider factors such as RAM, CPU cores, and storage capacity to ensure optimal performance and scalability.',
    options: [
      {
        key: '16g',
        title: '16 GB RAM, 8 cores, 320 GB SSD',
        value: 16785728,
        // valueStr: '1',
        selectable: true,
        priceUSD: 99,
        priceBVM: 140.65230260494243,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '32g',
        title: '32 GB RAM, 16 cores, 400 GB SSD',
        value: 33571216,
        // valueStr: '2',
        selectable: true,
        priceUSD: 499,
        priceBVM: 708.9444343420836,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '64g',
        title: '64 GB RAM, 32 cores, 650 GB SSD',
        value: 67142282,
        // valueStr: '3',
        selectable: true,
        priceUSD: 699,
        priceBVM: 993.0905002106541,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#12DAC2',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 2,
  },
  {
    id: '668f8ebf88f822fe3ebd3470',
    created_at: '2024-07-11T07:50:23.589Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'settlement',
    title: 'Base Layer',
    required: true,
    tooltip:
      'Select the base layer on which you want to build your blockchain. This will determine the base protocol and network characteristics, such as security, scalability, and consensus mechanisms.',
    options: [
      {
        key: 'bitcoin',
        title: 'Bitcoin',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'ethereum',
        title: 'Ethereum',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#F8B200',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'Base Layer',
    // whitelistAddress: null,
    order: 0,
  },
  {
    id: '668f8ebf88f822fe3ebd3471',
    created_at: '2024-07-11T07:50:23.694Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'compute',
    title: 'Compute',
    required: true,
    tooltip:
      'Choose the scaling solution tailored to your needs. Rollups enhance scalability and reduce transaction costs by processing transactions off-chain while posting transaction data on-chain.',
    options: [
      {
        key: 'zk',
        title: 'Zk Rollups',
        value: 21,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-explorer.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'op',
        title: 'Optimistic Rollups',
        value: 20,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-op.svg',
        // logo: '',
        needContactUs: true,
        order: 0,
      },
      {
        key: 'gpu',
        title: 'GPU Rollups',
        value: 22,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: '',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#A041FF',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 3,
  },
  {
    id: '668f8ebf88f822fe3ebd3472',
    created_at: '2024-07-11T07:50:23.774Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'storage',
    title: 'Storage',
    required: true,
    tooltip:
      'Ensure easy access to transaction details and smart contracts for all nodes on L1, L2, and even L3 networks. Using a separate DA layer reduces mainnet congestion, enhancing scalability, security, and transaction cost-efficiency.',
    options: [
      {
        key: 'bvm_da',
        title: 'BVM',
        value: 21,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-bvm.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'polygon',
        title: 'Polygon',
        value: 10,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-polygon.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'celestia',
        title: 'Celestia',
        value: 13,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-ceslestia.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'avail',
        title: 'Avail',
        value: 18,
        // valueStr: '',
        selectable: true,
        priceUSD: 10,
        priceBVM: 14.207303293428529,
        tooltip: '',
        supportNetwork: 'testnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-avail.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'filecoin',
        title: 'Filecoin',
        value: 21,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-filecoin.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'near_da',
        title: 'Near',
        value: 15,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-near.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#15C888',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'DA',
    // whitelistAddress: null,
    order: 4,
  },
  {
    id: '668f8ebf88f822fe3ebd3473',
    created_at: '2024-07-11T07:50:23.844Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'zk_prover',
    title: 'ZK Prover',
    required: false,
    tooltip:
      "Prover is a crucial component responsible for generating cryptographic proofs that verify the correctness of transactions processed off-chain by the blockchain's sequencer.",
    options: [
      {
        key: 'zk_prover',
        title: 'ZK Prover',
        value: 1,
        // valueStr: '',
        selectable: true,
        priceUSD: 1300,
        priceBVM: 1846.9494281457087,
        tooltip: '',
        supportNetwork: '',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-explorer.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#15BDC8',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 7,
  },
  {
    id: '668f8ebf88f822fe3ebd3474',
    created_at: '2024-07-11T07:50:23.919Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'block_gas_limit',
    title: 'Block Gas Limit',
    required: true,
    tooltip:
      'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume. By default, it is set to 30,000,000, but you can adjust it according to your specific needs.',
    options: [
      {
        key: '1m',
        title: '1,000,000,000',
        value: 1000000000,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-min.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '2m',
        title: '2,000,000,000',
        value: 2000000000,
        // valueStr: '',
        selectable: true,
        priceUSD: 5,
        priceBVM: 7.1036516467142645,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-medium.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '4m',
        title: '4,000,000,000',
        value: 4000000000,
        // valueStr: '',
        selectable: true,
        priceUSD: 10,
        priceBVM: 14.207303293428529,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-max.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#FB9F00',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'Block Gas Limit',
    // whitelistAddress: null,
    order: 5,
  },
  {
    id: '668f8ebf88f822fe3ebd3475',
    created_at: '2024-07-11T07:50:23.993Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'withdrawal_time',
    title: 'Withdrawal Time',
    required: true,
    tooltip:
      'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to the L1.',
    options: [
      {
        key: '12h',
        title: '12 hours',
        value: 43200,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-slow.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '4h',
        title: '4 hours',
        value: 14400,
        // valueStr: '',
        selectable: true,
        priceUSD: 5,
        priceBVM: 7.1036516467142645,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-fast.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '2h',
        title: '2 hours',
        value: 7200,
        // valueStr: '',
        selectable: true,
        priceUSD: 10,
        priceBVM: 14.207303293428529,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-superfast.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#F200F2',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'Withdrawal Time',
    // whitelistAddress: null,
    order: 6,
  },
  {
    id: '668f8ec088f822fe3ebd3476',
    created_at: '2024-07-11T07:50:24.072Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'wallet',
    title: 'Wallet',
    required: false,
    tooltip:
      'This module enhances user experience by allowing gas fees to be paid in different cryptocurrencies, eliminating the need to hold a specific one for transaction fees.',
    options: [
      {
        key: 'flex_pay',
        title: 'Flex Pay',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: '',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#00C1CD',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'Wallet',
    // whitelistAddress: null,
    order: 8,
  },
  {
    id: '668f8ec088f822fe3ebd3477',
    created_at: '2024-07-11T07:50:24.179Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'bridge_apps',
    title: 'Bridge Apps',
    required: false,
    tooltip:
      'Bring BTC, ETH, and other assets to your blockchain and transfer them back to Bitcoin and Ethereum networks.',
    options: [
      {
        key: 'btc_bridge',
        title: 'Bitcoin',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/btc_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'eth_bridge',
        title: 'Ethereum',
        value: 1,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/eth_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'solana_bridge',
        title: 'Solana',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-solana.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/solana_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'runes_bridge',
        title: 'Runes',
        value: 3,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-runes.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/runs_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'ordinals_bridge',
        title: 'Ordinals',
        value: 4,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-ordinals.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/ordinals_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#855AFF',
    type: 'module',
    disable: false,
    multiChoice: true,
    confuseWord: true,
    confuseIcon:
      'https://storage.googleapis.com/bvm-network/icons-tool/icon-bridge-confused.svg',
    confuseTitle: 'Your chain',
    // whitelistAddress: null,
    order: 9,
  },
  {
    id: '668f8ec088f822fe3ebd3478',
    created_at: '2024-07-11T07:50:24.299Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'defi_apps',
    title: 'DeFi Apps',
    required: false,
    tooltip:
      'Pre-install DeFi dapps to your blockchain, including token issuance, DEX, staking, and more to boost liquidity and attract users with essential financial services from the start.',
    options: [
      {
        key: 'issue_token',
        title: 'Issue a token',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'vesting',
        title: 'Vesting',
        value: 1,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-vesting.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'staking',
        title: 'Staking',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-staking.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'dex',
        title: 'DEX',
        value: 3,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-dex.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'orderbook',
        title: 'Orderbook',
        value: 4,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'perpeptual',
        title: 'Perpeptual',
        value: 5,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-perceptual.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#F76649',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 10,
  },
  {
    id: '668f8ec088f822fe3ebd3479',
    created_at: '2024-07-11T07:50:24.462Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'degen_apps',
    title: 'Degen Apps',
    required: false,
    tooltip:
      'Pre-install degen dapps to your blockchain to attract attention and increase user engagement.',
    options: [
      {
        key: 'yolo',
        title: 'YOLO',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'nft_raffle',
        title: 'NFT Raffle',
        value: 1,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-raffle.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'mr_market',
        title: 'Mr. Markets',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-bull-bear.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#E6004D',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 11,
  },
  {
    id: '668f8ec088f822fe3ebd347a',
    created_at: '2024-07-11T07:50:24.535Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'gaming_apps',
    title: 'Gaming Apps',
    required: false,
    tooltip:
      'Pre-install gaming dapps for a fun and immersive experience. Introduce users to new and exciting on-chain games.',
    options: [
      {
        key: 'pepe_fight',
        title: 'Pepe Fight',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'merge',
        title: 'Merge',
        value: 1,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'blast',
        title: 'Blast',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'connect',
        title: 'Connect',
        value: 3,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#C000E6',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: [
    //   '0x2d66881F48Fe18c63C0CB52b3559FBf520287b2F',
    //   '0xb262df097f649cb962b6ee256b19eec51d77cfa8',
    // ],
    order: 12,
  },
];
