import { DappModel } from '@/types/customize-model';

export const accountAbstractionAsADapp: DappModel = {
  id: 'account_abstraction',
  key: 'account_abstraction',
  title: 'Account Abstraction',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#00c1cd',
  color_border: '#00c1cd',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'account_abstraction_info',
    title: 'Account Abstraction',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [
      {
        background: '#009aa5',
        key: 'input_apps_address',
        title: 'Token contract address',
        previewTitle: 'Address',
        type: 'input',
        icon: '',
        value: '',
        tooltip: '',
        options: [],
        placeholder: '0x0000000000000000000000',
      },
      {
        background: '#009aa5',
        key: 'input_apps_fee_rate',
        title: 'Tokens per gas',
        type: 'input',
        icon: '',
        value: '',
        tooltip: '',
        options: [],
        placeholder: '21,000',
      },
    ],
  },
};

export const dappMockupData: DappModel[] = [
  {
    id: 'token_generation',
    key: 'token_generation',
    title: 'Token Generation',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 2,
    color: '#f76649',
    color_border: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: true,
      },
      {
        key: 'tokenomics',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: 'Allocation',
        tooltip: '',
        required: false,
      },
      // {
      //   key: 'base_modules',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Base Modules',
      //   tooltip: 'Token module',
      //   required: false,
      // },
      // {
      //   key: 'modules',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Modules',
      //   tooltip: 'Token module',
      //   required: false,
      // },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Issue a token',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      background: '#F200F2',
      fields: [
        {
          background: '#F200F2',
          key: 'token_name',
          title: 'Token Name',
          previewTitle: 'Name',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: 'e.g YOUR TOKEN NO.1',
        },
        {
          background: '#368BDB',
          key: 'token_symbol',
          title: 'Symbol',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: 'e.g YTKN',
        },
        {
          background: '#0d2dd0',
          key: 'token_supply',
          title: 'Total Supply',
          previewTitle: 'Supply',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          inputType: 'number',
          placeholder: 'e.g 1,000,000,000',
        },
        {
          background: '#15C888',
          key: 'receiver_address',
          title: 'Receiver Address',
          previewTitle: 'Address',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: 'e.g 0x0000000000000000000000000000000000000000',
        },
        {
          key: 'logo',
          title: 'Logo',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: '',
          background: '#d2135c',
          inputType: 'file',
          inputAccept: 'image/*',
        },
        // {
        //   background: '#00AA6C',
        //   key: 'publish_date',
        //   title: 'Publish Date',
        //   previewTitle: 'Publish Date',
        //   type: 'datetime',
        //   icon: '',
        //   value: '',
        //   tooltip: '',
        //   options: [],
        // },
      ],
    },
    blockFields: [
      {
        key: 'allocation',
        title: 'Allocation',
        icon: '/icons-tool/issue-a-token/icon-allocation.svg',
        placableAmount: -1,
        section: 'tokenomics',
        preview: false,
        background: '#f76649',
        fields: [
          {
            background: '#c4513a',
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            placeholder: 'e.g Allocation Name',
          },
          {
            background: '#c4513a',
            key: 'total_amount',
            title: 'Amount',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            placeholder: 'e.g 100,000,000',
            inputType: 'number',
          },
          {
            background: '#c4513a',
            key: 'address',
            title: 'Receiver Address',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            placeholder: 'e.g 0x0000000000000000000000000000000000000000',
          },
          {
            key: 'is_vesting',
            title: 'Vesting',
            type: 'extends',
            icon: '',
            value: 1,
            tooltip: '',
            background: '#c4513a',
            options: [
              {
                key: 'cliff',
                title: 'Cliff',
                value: '',
                icon: '',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'cliff_unit',
                    title: 'Time',
                    value: '0',
                    icon: '',
                    tooltip: '',
                    type: 'dropdown',
                    level: 1,
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'cliff',
                    title: 'Amount',
                    level: 1,
                    value: '',
                    icon: '',
                    tooltip: '',
                    type: 'input',
                    options: [],
                    placeholder: 'e.g 36',
                    inputType: 'number',
                  },
                ],
              },
              {
                key: 'duration',
                title: 'Duration',
                value: '',
                icon: '',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'duration_unit',
                    title: 'Time',
                    value: '0',
                    icon: '',
                    tooltip: '',
                    type: 'dropdown',
                    level: 1,
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'duration',
                    title: 'Amount',
                    level: 1,
                    value: '',
                    icon: '',
                    tooltip: '',
                    type: 'input',
                    options: [],
                    placeholder: 'e.g 36',
                    inputType: 'number',
                  },
                ],
              },
            ],
          },
          // {
          //   background: '#F8B200',
          //   key: 'address',
          //   title: 'Receiver Address',
          //   previewTitle: 'Address',
          //   type: 'input',
          //   icon: '',
          //   value: '',
          //   tooltip: '',
          //   options: [],
          //   placeholder: 'e.g 0x0000000000000000000000000000000000000000',
          // },
          // {
          //   key: 'is_vesting',
          //   title: 'Vesting',
          //   type: 'extends',
          //   icon: '',
          //   value: 0,
          //   tooltip: '',
          //   background: '#F8B200',
          //   options: [
          //     {
          //       key: 'cliff',
          //       title: 'Cliff',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'cliff_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'cliff',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //         },
          //       ],
          //     },
          //     {
          //       key: 'duration',
          //       title: 'Duration',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'duration_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'duration',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //         },
          //       ],
          //     },
          //   ],
          // },
        ],
        childrenFields: [
          // {
          //   background: '#c4513a',
          //   key: 'address',
          //   title: 'Receiver Address',
          //   type: 'input',
          //   icon: '',
          //   value: '',
          //   tooltip: '',
          //   options: [],
          //   placeholder: 'e.g 0x0000000000000000000000000000000000000000',
          // },
          // {
          //   key: 'is_vesting',
          //   title: 'Vesting',
          //   type: 'extends',
          //   icon: '',
          //   value: 1,
          //   tooltip: '',
          //   background: '#c4513a',
          //   options: [
          //     {
          //       key: 'cliff',
          //       title: 'Cliff',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'cliff_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'cliff',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //           inputType: 'number',
          //         },
          //       ],
          //     },
          //     {
          //       key: 'duration',
          //       title: 'Duration',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'duration_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'duration',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //           inputType: 'number',
          //         },
          //       ],
          //     },
          //   ],
          // },
        ],
      },
    ],
    singleFields: [
      // {
      //   title: 'Total Supply',
      //   key: 'token_supply',
      //   icon: '',
      //   fields: [
      //     {
      //       key: 'token_supply',
      //       title: 'Total Supply',
      //       type: 'input',
      //       icon: '',
      //       value: '',
      //       tooltip: '',
      //       options: [],
      //       placeholder: 'e.g 1,000,000,000',
      //       background: '#c4513a',
      //       inputType: 'number',
      //     },
      //   ],
      //   placableAmount: 1,
      //   preview: false,
      //   section: 'information',
      //   background: '#c4513a',
      // },
      // {
      //   title: 'Receiver Address',
      //   key: 'receiver_address',
      //   icon: '',
      //   fields: [
      //     {
      //       key: 'receiver_address',
      //       title: 'Receiver Address',
      //       type: 'input',
      //       icon: '',
      //       value: '',
      //       tooltip: '',
      //       options: [],
      //       placeholder: 'e.g 0x0000000000000000000000000000000000000000',
      //       background: '#c4513a',
      //     },
      //   ],
      //   placableAmount: 1,
      //   preview: false,
      //   section: 'information',
      //   background: '#c4513a',
      // },
      // {
      //   title: 'Logo',
      //   key: 'logo',
      //   icon: '',
      //   fields: [
      //     {
      //       key: 'logo',
      //       title: 'Logo',
      //       type: 'input',
      //       icon: '',
      //       value: '',
      //       tooltip: '',
      //       options: [],
      //       placeholder: '',
      //       background: '#c4513a',
      //       inputType: 'file',
      //       inputAccept: 'image/*',
      //     },
      //   ],
      //   placableAmount: 1,
      //   preview: false,
      //   section: 'information',
      //   background: '#c4513a',
      // },
    ],
    // moduleFields: [
    //   {
    //     preview: false,
    //     key: 'number_module',
    //     title: 'Number',
    //     icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //     placableAmount: -1,
    //     section: 'modules',
    //     fields: [
    //       {
    //         key: '1',
    //         title: 'Number 1',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '1',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '2',
    //         title: 'Number 2',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '2',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '3',
    //         title: 'Number 3',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '3',
    //         tooltip: '',
    //         options: [],
    //       },
    //     ],
    //   },
    // ],
    // baseModuleFields: [
    //   {
    //     preview: false,
    //     key: 'number_module',
    //     title: 'Number',
    //     icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //     placableAmount: -1,
    //     section: 'base_modules',
    //     fields: [
    //       {
    //         key: '1',
    //         title: 'Number 1',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '1',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '2',
    //         title: 'Number 2',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '2',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '3',
    //         title: 'Number 3',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '3',
    //         tooltip: '',
    //         options: [],
    //       },
    //     ],
    //   },
    // ],
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-staking.svg',
    order: 3,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: '',
    },
    sections: [
      {
        key: 'staking_token',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Token',
        tooltip: '',
        required: true,
      },
      {
        key: 'reward_token',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Reward Token',
        tooltip: '',
        required: true,
      },
      {
        key: 'info',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Reward Rate',
        tooltip: '',
        required: true,
      },
    ],
    baseModuleFields: [
      {
        key: 'staking_token',
        title: 'Staking Token',
        icon: '',
        placableAmount: -1,
        section: 'staking_token',
        preview: false,
        background: '#A041FF',
        fields: [
          {
            key: 'bvm',
            title: 'BVM', // symbol
            value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
          // {
          //   key: 'eth',
          //   title: 'ETH (Upgrade plan 99$)', // symbol
          //   value: '0x1234', // contract_address
          //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
          //   tooltip: '',
          //   type: '',
          //   options: [],
          //   selectable: false,
          // },
        ],
      },
    ],
    moduleFields: [
      {
        key: 'reward_token',
        title: 'Reward Token',
        icon: '',
        preview: false,
        placableAmount: 1,
        section: 'reward_token',
        background: '#15C888',
        fields: [
          {
            key: 'bvm',
            title: 'BVM', // symbol
            value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
          // {
          //   key: 'eth',
          //   title: 'ETH (Upgrade plan 99$)', // symbol
          //   value: '0x1234', // contract_address
          //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
          //   tooltip: '',
          //   type: '',
          //   options: [],
          //   selectable: false,
          // },
        ],
      },
    ],
    blockFields: [
      {
        key: 'info',
        title: 'Reward rate',
        icon: '',
        placableAmount: 1,
        section: 'info',
        preview: false,
        background: '#C44127',
        fields: [
          {
            key: 'rate',
            title: 'Rate',
            inputType: 'number',
            type: 'input',
            icon: '',
            value: '',
            tooltip: 'Exchange rate between staking token and reward token.',
            placeholder: 'eg. 1',
            options: [],
            background: '#C44127',
          },
          {
            key: 'apr',
            title: 'APR',
            type: 'input',
            inputType: 'number',
            icon: '',
            value: '',
            tooltip: '',
            placeholder: 'eg. 20%',
            options: [],
            background: '#C44127',
          },
          {
            key: 'amount',
            title: 'Reward amount',
            previewTitle: 'Reward',
            inputType: 'number',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            placeholder: 'eg. 100,000',
            options: [],
            background: '#C44127',
          },
        ],
      },
    ],
    baseBlock: {
      key: '',
      title: 'Create a Staking Pool',
      icon: '',
      placableAmount: -1,
      section: '',
      preview: false,
      fields: [],
    },
  },
  {
    id: 'airdrop',
    key: 'airdrop',
    title: 'Airdrop',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
    order: 4,
    color: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Airdrop Token',
        tooltip: '',
        required: true,
      },
      // {
      //   key: 'tasks',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Whitelisted',
      //   tooltip: '',
      //   required: true,
      // },
    ],
    baseBlock: {
      preview: false,
      key: 'information',
      title: 'Token for Airdrop',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
      placableAmount: -1,
      section: 'information',
      fields: [
        {
          key: 'airdrop_title',
          title: 'Title',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'reward_token',
          title: 'Token',
          type: 'dropdown',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'airdrop_amount',
          title: 'Reward',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          inputType: 'number',
          options: [],
        },
      ],
    },
    singleFields: [
      {
        title: 'Start Date',
        key: 'start_date',
        icon: '',
        background: '#c4513a',
        fields: [
          {
            key: 'start_date',
            title: 'Start date',
            previewTitle: 'Start',
            type: 'datetime',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            selectable: true,
            background: '#c4513a',
          },
        ],
        placableAmount: 1,
        preview: false,
        section: 'information',
      },
      {
        title: 'End Date',
        key: 'end_date',
        icon: '',
        background: '#c4513a',
        fields: [
          {
            key: 'end_date',
            title: 'End date',
            previewTitle: 'End',
            type: 'datetime',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            background: '#c4513a',
          },
        ],
        placableAmount: 1,
        preview: false,
        section: 'information',
      },
      {
        title: 'Shared holder',
        key: 'is_bvm_shard',
        icon: '',
        background: '#c4513a',
        fields: [
          {
            key: 'is_bvm_shard',
            title: 'Shared holder',
            type: 'extends',
            icon: '',
            value: 1,
            tooltip: '',
            options: [],
            disabled: true,
            background: '#c4513a',
          },
        ],
        placableAmount: 1,
        preview: false,
        section: 'information',
      },
    ],
  },
  {
    id: 'yolo',
    key: 'yolo',
    title: 'YOLO',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
    order: 5,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: '',
    },
    sections: [
      {
        key: 'yolo',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'YOLO',
        tooltip: '',
        required: true,
      },
      // {
      //   key: 'reward_token',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Reward Token',
      //   tooltip: '',
      //   required: true,
      // },
      // {
      //   key: 'info',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Reward Rate',
      //   tooltip: '',
      //   required: true,
      // },
    ],
    baseModuleFields: [
      {
        key: 'settlement_token',
        title: 'Settlement Token',
        icon: '',
        placableAmount: -1,
        section: 'yolo',
        preview: false,
        background: '#A041FF',
        fields: [
          {
            key: 'bvm',
            title: 'BVM', // symbol
            value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
          // {
          //   key: 'eth',
          //   title: 'ETH (Upgrade plan 99$)', // symbol
          //   value: '0x1234', // contract_address
          //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
          //   tooltip: '',
          //   type: '',
          //   options: [],
          //   selectable: false,
          // },
        ],
      },
    ],
    baseBlock: {
      key: '',
      title: 'Create a YOLO Game',
      icon: '',
      placableAmount: -1,
      section: '',
      preview: false,
      fields: [
        {
          key: 'value_per_entry',
          title: 'Value Per Entry',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Number of token per entry',
          placeholder: 'eg. 300',
          options: [],
          background: '#C44127',
        },
        {
          key: 'round_duration',
          title: 'Round Duration',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Round duration in second',
          placeholder: 'eg. 300',
          options: [],
          background: '#00AA6C',
        },
        {
          key: 'maximum_participants',
          title: 'Maximum Participants',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Maximum participants per round',
          placeholder: 'eg. 500',
          options: [],
          background: '#0d2dd0',
        },
        {
          key: 'protocol_fee_ratio',
          title: 'Protocol Fee Ratio',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Protocol Fee Ratio',
          placeholder: 'eg. 0.1',
          options: [],
          background: '#C44127',
        },
      ],
    },
  },
];

// <baseIndex>-<type>-<fieldKey>-<level>-<index>-<blockKey>
export const dappTemplateFormMockupData = {
  dappKey: 'token_generation',
  fieldValue: {
    '0-base-token_name-0': 'BVM',
    '0-base-token_symbol-0': 'BVM',
    '0-base-token_supply-0': '1000000000',
    '0-block-name-0-0-allocation': 'Airdrop',
    '0-block-total_amount-0-0-allocation': '300000',
    '0-block-address-0-0-allocation': '0x1234',
    '0-block-is_vesting-0-0-allocation': true,
    '0-block-cliff_unit-1-0-allocation': '0',
    '0-block-cliff-1-0-allocation': '10',
    '0-block-duration_unit-1-0-allocation': '1',
    '0-block-duration-1-0-allocation': '10',

    '1-base-token_name-0': 'Meme',
    '1-base-token_symbol-0': 'MEM',
    '1-base-token_supply-0': '100000000000000',
    '1-block-name-0-0-allocation': 'Airdrop',
    '1-block-total_amount-0-0-allocation': '100000000000000',
    '1-block-address-0-0-allocation': '0x1231',
    '1-block-is_vesting-0-0-allocation': false,
  },
};

export const stakingTemplateFormMockupData = [
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'Stopped',
      color: '#000',
      background: '#00AA6C',
      status: 'stopped',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '12%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'Stopped',
      color: '',
      background: '',
      status: 'stopped',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '50%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '23%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Stopped',
      color: '#bdbdbd',
      background: '#212d28',
      // color: '',
      // background: '',
      status: 'stopped',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '25%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '10%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '25%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '25%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
];
