import { WalletType } from '@/stores/states/dapp/types';
import { DappModel } from '@/types/customize-model';

export const createAgentGeneralIdeaAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'general_idea',
  key: 'general_idea',
  title: 'Agent information',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#C44127',
  color_border: '#C44127',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'General Idea',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const createAgentNftEtherAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'nft_ether',
  key: 'nft_ether',
  title: 'NFT (Ethereum)',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#00c1cd',
  color_border: '#00c1cd',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'NFT (Ethereum)',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const createAgentNftOrdinalBTCAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'ordinal_bitcoin',
  key: 'ordinal_bitcoin',
  title: 'Ordinals (Bitcoin)',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#00c1cd',
  color_border: '#00c1cd',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'Ordinals (Bitcoin)',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const createAgentTokensPumpAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'tokens_pump_fun',
  key: 'tokens_pump_fun',
  title: 'Tokens Pump',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#00c1cd',
  color_border: '#00c1cd',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'Tokens Pump',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const missionAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'mission',
  key: 'mission',
  title: 'Mission',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#855AFF',
  color_border: '#855AFF',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'mission',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'mission_info',
    title: 'Mission',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'missions',
    preview: false,
    background: '#855AFF',
    fields: [],
  },
  blockFields: [
    {
      key: 'post',
      title: 'Post',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: 1,
      section: 'missions',
      preview: false,
      background: '#855AFF',
      fields: [
        {
          background: '#855AFF',
          key: 'network',
          title: 'Network',
          type: 'dropdown',
          icon: '',
          value: 'twitter',
          tooltip: '',
          options: [
            {
              key: 'twitter',
              title: 'Twitter',
              value: 'twitter',
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
              tooltip: '',
              options: [],
              type: '',
            },
            {
              key: 'farcaster',
              title: 'Farcaster',
              value: 'farcaster',
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          background: '#855AFF',
          key: 'time',
          title: 'Time',
          type: 'input',
          icon: '',
          value: '10',
          tooltip: '',
          options: [],
          placeholder: 'e.g 10',
          inputType: 'number',
        },
        {
          background: '#855AFF',
          key: 'model',
          title: 'Model',
          type: 'dropdown',
          icon: '',
          value: 'llama3',
          tooltip: '',
          options: [
            {
              key: 'llama3',
              title: 'Llama3',
              value: 'llama3',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          background: '#855AFF',
          key: 'description',
          title: 'Description',
          type: 'textarea',
          icon: '',
          value: 'Happy',
          tooltip: '',
          options: [],
          placeholder: 'Happy',
        },
      ],
    },
  ],
};

export const dappMockupData: DappModel[] = [
  // Post
  {
    id: 'post',
    key: 'post',
    title: 'Post',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 4,
    color: '#f76649',
    color_border: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'post',
      title: 'Post',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: 1,
      section: 'information',
      preview: false,
      background: '#F200F2',
      fields: [
        {
          key: 'network',
          title: 'Network',
          previewTitle: 'Name',
          type: 'dropdown',
          icon: '',
          value: 'twitter',
          tooltip: '',
          options: [
            {
              key: 'twitter',
              title: 'Twitter',
              value: 'twitter',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
            {
              key: 'farcaster',
              title: 'Farcaster',
              value: 'farcaster',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'time',
          title: 'Time',
          type: 'input',
          icon: '',
          value: '10',
          tooltip: '',
          options: [],
          placeholder: 'e.g 10',
          inputType: 'number',
        },
        {
          key: 'model',
          title: 'Model',
          type: 'dropdown',
          icon: '',
          value: 'llama3',
          tooltip: '',
          options: [
            {
              key: 'llama3',
              title: 'Llama3',
              value: 'llama3',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'description',
          title: 'Description',
          type: 'textarea',
          icon: '',
          value: 'Happy',
          tooltip: '',
          options: [],
          placeholder: 'Happy',
        },
      ],
    },
  },

  // Reply to mentions
  {
    id: 'reply_mention',
    key: 'reply_mention',
    title: 'Reply to mentions',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 4,
    color: '#f76649',
    color_border: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'reply_mention',
      title: 'Reply to mentions',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: 1,
      section: 'information',
      preview: false,
      background: '#F200F2',
      fields: [
        {
          key: 'network',
          title: 'Network',
          previewTitle: 'Name',
          type: 'dropdown',
          icon: '',
          value: 'twitter',
          tooltip: '',
          options: [
            {
              key: 'twitter',
              title: 'Twitter',
              value: 'twitter',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
            {
              key: 'farcaster',
              title: 'Farcaster',
              value: 'farcaster',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'time',
          title: 'Time',
          type: 'input',
          icon: '',
          value: '10',
          tooltip: '',
          options: [],
          placeholder: 'e.g 10',
          inputType: 'number',
        },
        {
          key: 'model',
          title: 'Model',
          type: 'dropdown',
          icon: '',
          value: 'llama3',
          tooltip: '',
          options: [
            {
              key: 'llama3',
              title: 'Llama3',
              value: 'llama3',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'description',
          title: 'Description',
          type: 'textarea',
          icon: '',
          value: 'Happy',
          tooltip: '',
          options: [],
          placeholder: 'Happy',
        },
      ],
    },
  },

  // Engage
  {
    id: 'engage',
    key: 'engage',
    title: 'Engage',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 4,
    color: '#f76649',
    color_border: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'engage',
      title: 'Engage',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: 1,
      section: 'information',
      preview: false,
      background: '#F200F2',
      fields: [
        {
          key: 'network',
          title: 'Network',
          previewTitle: 'Name',
          type: 'dropdown',
          icon: '',
          value: 'twitter',
          tooltip: '',
          options: [
            {
              key: 'twitter',
              title: 'Twitter',
              value: 'twitter',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
            {
              key: 'farcaster',
              title: 'Farcaster',
              value: 'farcaster',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'time',
          title: 'Time',
          type: 'input',
          icon: '',
          value: '10',
          tooltip: '',
          options: [],
          placeholder: 'e.g 10',
          inputType: 'number',
        },
        {
          key: 'model',
          title: 'Model',
          type: 'dropdown',
          icon: '',
          value: 'llama3',
          tooltip: '',
          options: [
            {
              key: 'llama3',
              title: 'Llama3',
              value: 'llama3',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'description',
          title: 'Description',
          type: 'textarea',
          icon: '',
          value: 'Happy',
          tooltip: '',
          options: [],
          placeholder: 'Happy',
        },
      ],
    },
  },

  // Follows
  {
    id: 'follow',
    key: 'follow',
    title: 'Follows',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 4,
    color: '#f76649',
    color_border: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'follow',
      title: 'Follows',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: 1,
      section: 'information',
      preview: false,
      background: '#F200F2',
      fields: [
        {
          key: 'network',
          title: 'Network',
          previewTitle: 'Name',
          type: 'dropdown',
          icon: '',
          value: 'twitter',
          tooltip: '',
          options: [
            {
              key: 'twitter',
              title: 'Twitter',
              value: 'twitter',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
            {
              key: 'farcaster',
              title: 'Farcaster',
              value: 'farcaster',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'time',
          title: 'Time',
          type: 'input',
          icon: '',
          value: '10',
          tooltip: '',
          options: [],
          placeholder: 'e.g 10',
          inputType: 'number',
        },
        {
          key: 'model',
          title: 'Model',
          type: 'dropdown',
          icon: '',
          value: 'llama3',
          tooltip: '',
          options: [
            {
              key: 'llama3',
              title: 'Llama3',
              value: 'llama3',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'description',
          title: 'Description',
          type: 'textarea',
          icon: '',
          value: 'Happy',
          tooltip: '',
          options: [],
          placeholder: 'Happy',
        },
      ],
    },
  },

  // News
  {
    id: 'news',
    key: 'news',
    title: 'News',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 4,
    color: '#f76649',
    color_border: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'news',
      title: 'News',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: 1,
      section: 'information',
      preview: false,
      background: '#F200F2',
      fields: [
        {
          key: 'network',
          title: 'Network',
          previewTitle: 'Name',
          type: 'dropdown',
          icon: '',
          value: 'twitter',
          tooltip: '',
          options: [
            {
              key: 'twitter',
              title: 'Twitter',
              value: 'twitter',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
            {
              key: 'farcaster',
              title: 'Farcaster',
              value: 'farcaster',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'time',
          title: 'Time',
          type: 'input',
          icon: '',
          value: '10',
          tooltip: '',
          options: [],
          placeholder: 'e.g 10',
          inputType: 'number',
        },
        {
          key: 'model',
          title: 'Model',
          type: 'dropdown',
          icon: '',
          value: 'llama3',
          tooltip: '',
          options: [
            {
              key: 'llama3',
              title: 'Llama3',
              value: 'llama3',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          key: 'description',
          title: 'Description',
          type: 'textarea',
          icon: '',
          value: 'Happy',
          tooltip: '',
          options: [],
          placeholder: 'Happy',
        },
      ],
    },
  },
];
