import { WalletType } from '@/stores/states/dapp/types';
import { DappModel } from '@/types/customize-model';

export const createAgentGeneralIdeaAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'general_idea',
  key: 'general_idea',
  title: 'Agent information',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#C44127',
  color_border: '#C44127',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'General Idea',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const createAgentNftEtherAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'nft_ether',
  key: 'nft_ether',
  title: 'NFT (Ethereum)',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#00c1cd',
  color_border: '#00c1cd',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'NFT (Ethereum)',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const createAgentNftOrdinalBTCAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'ordinal_bitcoin',
  key: 'ordinal_bitcoin',
  title: 'Ordinals (Bitcoin)',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#00c1cd',
  color_border: '#00c1cd',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'Ordinals (Bitcoin)',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const createAgentTokensPumpAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'tokens_pump_fun',
  key: 'tokens_pump_fun',
  title: 'Tokens Pump',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#00c1cd',
  color_border: '#00c1cd',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'agent_information_info',
    title: 'Tokens Pump',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'information',
    preview: false,
    background: '#00C1CD',
    fields: [],
  },
};

export const missionAsBrainstorm: DappModel = {
  isDefaultDapp: true,
  id: 'mission',
  key: 'mission',
  title: 'Mission',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#855AFF',
  color_border: '#855AFF',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'mission',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'mission_info',
    title: 'Mission',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'missions',
    preview: false,
    background: '#855AFF',
    fields: [],
  },
  blockFields: [
    {
      key: 'post',
      title: 'Post',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: 1,
      section: 'missions',
      preview: false,
      background: '#855AFF',
      fields: [
        {
          background: '#855AFF',
          key: 'network',
          title: 'Network',
          type: 'dropdown',
          icon: '',
          value: 'twitter',
          tooltip: '',
          options: [
            {
              key: 'twitter',
              title: 'Twitter',
              value: 'twitter',
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
              tooltip: '',
              options: [],
              type: '',
            },
            {
              key: 'farcaster',
              title: 'Farcaster',
              value: 'farcaster',
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          background: '#855AFF',
          key: 'time',
          title: 'Time',
          type: 'input',
          icon: '',
          value: '10',
          tooltip: '',
          options: [],
          placeholder: 'e.g 10',
          inputType: 'number',
        },
        {
          background: '#855AFF',
          key: 'model',
          title: 'Model',
          type: 'dropdown',
          icon: '',
          value: 'llama3',
          tooltip: '',
          options: [
            {
              key: 'llama3',
              title: 'Llama3',
              value: 'llama3',
              icon: '',
              tooltip: '',
              options: [],
              type: '',
            },
          ],
        },
        {
          background: '#855AFF',
          key: 'description',
          title: 'Description',
          type: 'input',
          icon: '',
          value: 'Happy',
          tooltip: '',
          options: [],
          placeholder: 'Happy',
        },
      ],
    },
  ],
};

export const gamingAppsAsADapp: DappModel = {
  isDefaultDapp: true,
  id: 'gaming_apps',
  key: 'gaming_apps',
  title: 'Gaming Apps',
  icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
  order: 1,
  color: '#FFB800',
  color_border: '#FFB800',
  created_at: '2021-09-14T09:00:00.000Z',
  updated_at: '2021-09-14T09:00:00.000Z',
  tooltip: '',
  label: {
    title: '',
    color: '',
    background: '',
    status: '',
  },
  sections: [
    {
      key: 'modules',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      title: '',
      tooltip: '',
      required: false,
    },
  ],
  baseBlock: {
    key: 'gaming_apps_info',
    title: 'Game Apps',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    placableAmount: 1,
    section: 'missions',
    preview: false,
    background: '#FFB800',
    fields: [],
  },
};

export const dappMockupData: DappModel[] = [
  {
    id: 'token_generation',
    key: 'token_generation',
    title: 'Token Generation',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 4,
    color: '#f76649',
    color_border: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: true,
      },
      {
        key: 'tokenomics',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: 'Allocation',
        tooltip: '',
        required: false,
      },
      // {
      //   key: 'base_modules',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Base Modules',
      //   tooltip: 'Token module',
      //   required: false,
      // },
      // {
      //   key: 'modules',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Modules',
      //   tooltip: 'Token module',
      //   required: false,
      // },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Issue a token',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: false,
      background: '#F200F2',
      fields: [
        {
          background: '#F200F2',
          key: 'token_name',
          title: 'Token Name',
          previewTitle: 'Name',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: 'e.g YOUR TOKEN NO.1',
        },
        {
          background: '#368BDB',
          key: 'token_symbol',
          title: 'Symbol',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: 'e.g YTKN',
        },
        {
          background: '#0d2dd0',
          key: 'token_supply',
          title: 'Total Supply',
          previewTitle: 'Supply',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          inputType: 'number',
          placeholder: 'e.g 1,000,000,000',
        },
        {
          background: '#15C888',
          key: 'receiver_address',
          title: 'Receiver Address',
          previewTitle: 'Address',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: 'e.g 0x0000000000000000000000000000000000000000',
        },
        {
          key: 'logo',
          title: 'Logo',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
          placeholder: '',
          background: '#d2135c',
          inputType: 'file',
          inputAccept: 'image/*',
        },
        // {
        //   background: '#00AA6C',
        //   key: 'publish_date',
        //   title: 'Publish Date',
        //   previewTitle: 'Publish Date',
        //   type: 'datetime',
        //   icon: '',
        //   value: '',
        //   tooltip: '',
        //   options: [],
        // },
      ],
    },
    blockFields: [
      {
        key: 'allocation',
        title: 'Allocation',
        icon: '/icons-tool/issue-a-token/icon-allocation.svg',
        placableAmount: -1,
        section: 'tokenomics',
        preview: false,
        background: '#f76649',
        fields: [
          {
            background: '#c4513a',
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            placeholder: 'e.g Allocation Name',
          },
          {
            background: '#c4513a',
            key: 'total_amount',
            title: 'Amount',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            placeholder: 'e.g 100,000,000',
            inputType: 'number',
          },
          {
            background: '#c4513a',
            key: 'address',
            title: 'Receiver Address',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
            placeholder: 'e.g 0x0000000000000000000000000000000000000000',
          },
          {
            key: 'is_vesting',
            title: 'Vesting',
            type: 'extends',
            icon: '',
            value: 1,
            tooltip: '',
            background: '#c4513a',
            options: [
              {
                key: 'cliff',
                title: 'Cliff',
                value: '',
                icon: '',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'cliff_unit',
                    title: 'Time',
                    value: '0',
                    icon: '',
                    tooltip: '',
                    type: 'dropdown',
                    level: 1,
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'cliff',
                    title: 'Amount',
                    level: 1,
                    value: '',
                    icon: '',
                    tooltip: '',
                    type: 'input',
                    options: [],
                    placeholder: 'e.g 36',
                    inputType: 'number',
                  },
                ],
              },
              {
                key: 'duration',
                title: 'Duration',
                value: '',
                icon: '',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'duration_unit',
                    title: 'Time',
                    value: '0',
                    icon: '',
                    tooltip: '',
                    type: 'dropdown',
                    level: 1,
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'duration',
                    title: 'Amount',
                    level: 1,
                    value: '',
                    icon: '',
                    tooltip: '',
                    type: 'input',
                    options: [],
                    placeholder: 'e.g 36',
                    inputType: 'number',
                  },
                ],
              },
            ],
          },
          // {
          //   background: '#F8B200',
          //   key: 'address',
          //   title: 'Receiver Address',
          //   previewTitle: 'Address',
          //   type: 'input',
          //   icon: '',
          //   value: '',
          //   tooltip: '',
          //   options: [],
          //   placeholder: 'e.g 0x0000000000000000000000000000000000000000',
          // },
          // {
          //   key: 'is_vesting',
          //   title: 'Vesting',
          //   type: 'extends',
          //   icon: '',
          //   value: 0,
          //   tooltip: '',
          //   background: '#F8B200',
          //   options: [
          //     {
          //       key: 'cliff',
          //       title: 'Cliff',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'cliff_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'cliff',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //         },
          //       ],
          //     },
          //     {
          //       key: 'duration',
          //       title: 'Duration',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'duration_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'duration',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //         },
          //       ],
          //     },
          //   ],
          // },
        ],
        childrenFields: [
          // {
          //   background: '#c4513a',
          //   key: 'address',
          //   title: 'Receiver Address',
          //   type: 'input',
          //   icon: '',
          //   value: '',
          //   tooltip: '',
          //   options: [],
          //   placeholder: 'e.g 0x0000000000000000000000000000000000000000',
          // },
          // {
          //   key: 'is_vesting',
          //   title: 'Vesting',
          //   type: 'extends',
          //   icon: '',
          //   value: 1,
          //   tooltip: '',
          //   background: '#c4513a',
          //   options: [
          //     {
          //       key: 'cliff',
          //       title: 'Cliff',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'cliff_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'cliff',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //           inputType: 'number',
          //         },
          //       ],
          //     },
          //     {
          //       key: 'duration',
          //       title: 'Duration',
          //       value: '',
          //       icon: '',
          //       tooltip: '',
          //       type: 'group',
          //       options: [
          //         {
          //           key: 'duration_unit',
          //           title: 'Time',
          //           value: '0',
          //           icon: '',
          //           tooltip: '',
          //           type: 'dropdown',
          //           level: 1,
          //           options: [
          //             {
          //               key: 'day',
          //               title: 'Day',
          //               value: '0',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'week',
          //               title: 'Week',
          //               value: '1',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //             {
          //               key: 'month',
          //               title: 'Month',
          //               value: '2',
          //               icon: '',
          //               tooltip: '',
          //               type: '',
          //               options: [],
          //             },
          //           ],
          //         },
          //         {
          //           key: 'duration',
          //           title: 'Amount',
          //           level: 1,
          //           value: '',
          //           icon: '',
          //           tooltip: '',
          //           type: 'input',
          //           options: [],
          //           placeholder: 'e.g 36',
          //           inputType: 'number',
          //         },
          //       ],
          //     },
          //   ],
          // },
        ],
      },
    ],
    singleFields: [
      // {
      //   title: 'Total Supply',
      //   key: 'token_supply',
      //   icon: '',
      //   fields: [
      //     {
      //       key: 'token_supply',
      //       title: 'Total Supply',
      //       type: 'input',
      //       icon: '',
      //       value: '',
      //       tooltip: '',
      //       options: [],
      //       placeholder: 'e.g 1,000,000,000',
      //       background: '#c4513a',
      //       inputType: 'number',
      //     },
      //   ],
      //   placableAmount: 1,
      //   preview: false,
      //   section: 'information',
      //   background: '#c4513a',
      // },
      // {
      //   title: 'Receiver Address',
      //   key: 'receiver_address',
      //   icon: '',
      //   fields: [
      //     {
      //       key: 'receiver_address',
      //       title: 'Receiver Address',
      //       type: 'input',
      //       icon: '',
      //       value: '',
      //       tooltip: '',
      //       options: [],
      //       placeholder: 'e.g 0x0000000000000000000000000000000000000000',
      //       background: '#c4513a',
      //     },
      //   ],
      //   placableAmount: 1,
      //   preview: false,
      //   section: 'information',
      //   background: '#c4513a',
      // },
      // {
      //   title: 'Logo',
      //   key: 'logo',
      //   icon: '',
      //   fields: [
      //     {
      //       key: 'logo',
      //       title: 'Logo',
      //       type: 'input',
      //       icon: '',
      //       value: '',
      //       tooltip: '',
      //       options: [],
      //       placeholder: '',
      //       background: '#c4513a',
      //       inputType: 'file',
      //       inputAccept: 'image/*',
      //     },
      //   ],
      //   placableAmount: 1,
      //   preview: false,
      //   section: 'information',
      //   background: '#c4513a',
      // },
    ],
    // moduleFields: [
    //   {
    //     preview: false,
    //     key: 'number_module',
    //     title: 'Number',
    //     icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //     placableAmount: -1,
    //     section: 'missions',
    //     fields: [
    //       {
    //         key: '1',
    //         title: 'Number 1',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '1',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '2',
    //         title: 'Number 2',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '2',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '3',
    //         title: 'Number 3',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '3',
    //         tooltip: '',
    //         options: [],
    //       },
    //     ],
    //   },
    // ],
    // baseModuleFields: [
    //   {
    //     preview: false,
    //     key: 'number_module',
    //     title: 'Number',
    //     icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //     placableAmount: -1,
    //     section: 'base_modules',
    //     fields: [
    //       {
    //         key: '1',
    //         title: 'Number 1',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '1',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '2',
    //         title: 'Number 2',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '2',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '3',
    //         title: 'Number 3',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '3',
    //         tooltip: '',
    //         options: [],
    //       },
    //     ],
    //   },
    // ],
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-staking.svg',
    order: 5,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: '',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: '',
        tooltip: '',
        required: false,
      },
    ],
    baseModuleFields: [],
    moduleFields: [],
    blockFields: [],
    baseBlock: {
      key: '',
      title: 'Create a Staking Pool',
      icon: '',
      placableAmount: -1,
      section: 'information',
      preview: false,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [
            {
              key: 'bvm',
              title: 'BVM', // symbol
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
              tooltip: '',
              type: '',
              options: [],
              selectable: true,
            },
          ],
          background: '#C001E6',
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [
            {
              key: 'bvm',
              title: 'BVM', // symbol
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
              tooltip: '',
              type: '',
              options: [],
              selectable: true,
            },
          ],
          background: '#865AFF',
        },
        {
          key: 'rate',
          title: 'Rate',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
          background: '#C44127',
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          inputType: 'number',
          icon: '',
          value: '',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
          background: '#C44127',
        },
        {
          key: 'amount',
          title: 'Reward amount',
          previewTitle: 'Reward',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
          background: '#C44127',
        },
      ],
    },
  },
  {
    id: 'airdrop',
    key: 'airdrop',
    title: 'Airdrop',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
    order: 6,
    color: '#f76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Airdrop Token',
        tooltip: '',
        required: true,
      },
      {
        key: 'tasks',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Tasks',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      preview: false,
      key: 'information',
      title: 'Token for Airdrop',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
      placableAmount: -1,
      section: 'information',
      fields: [
        {
          key: 'airdrop_title',
          title: 'Title',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'reward_token',
          title: 'Token',
          type: 'dropdown',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'airdrop_amount',
          title: 'Reward',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          inputType: 'number',
          options: [],
        },
        {
          key: 'start_date',
          title: 'Start Date',
          type: 'datetime',
          value: '',
          tooltip: '',
          icon: '',
          background: '#c4513a',
          options: [],
        },
        {
          key: 'end_date',
          title: 'End Date',
          type: 'datetime',
          value: '',
          tooltip: '',
          icon: '',
          background: '#c4513a',
          options: [],
        },
        {
          key: 'is_bvm_shard',
          title: 'Shared holder',
          type: 'extends',
          value: '',
          tooltip: '',
          icon: '',
          background: '#c4513a',
          options: [],
        },
      ],
    },
    singleFields: [],
  },
  {
    id: 'yologame',
    key: 'yologame',
    title: 'YOLO',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
    order: 7,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: '',
    },
    sections: [
      {
        key: 'yolo',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: '',
        tooltip: '',
        required: false,
        show: true,
      },
    ],
    baseModuleFields: [
      {
        key: 'settlement_token',
        title: 'Payment Token',
        icon: '',
        placableAmount: -1,
        section: 'yolo',
        preview: false,
        background: '#A041FF',
        fields: [
          {
            key: 'bvm',
            title: 'BVM', // symbol
            value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
          // {
          //   key: 'eth',
          //   title: 'ETH (Upgrade plan 99$)', // symbol
          //   value: '0x1234', // contract_address
          //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
          //   tooltip: '',
          //   type: '',
          //   options: [],
          //   selectable: true,
          // },
        ],
      },
    ],
    baseBlock: {
      key: '',
      title: 'Create a YOLO Game',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
      placableAmount: -1,
      section: '',
      preview: false,
      fields: [
        // {
        //   key: 'settlement_token',
        //   title: 'Settlement Token',
        //   type: 'dropdown',
        //   icon: '',
        //   value: '',
        //   tooltip: '',
        //   options: [],
        //   background: '#A041FF',
        // },
        {
          key: 'value_per_entry',
          title: 'Entry Cost (Tokens per Ticket)',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Enter the number of tokens required for each ticket/entry.',
          placeholder: 'eg. 1000',
          options: [],
          background: '#C44127',
        },
        {
          key: 'round_duration',
          title: 'Round Duration (Seconds)',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Set the duration of each round in seconds.',
          placeholder: 'eg. 300',
          options: [],
          background: '#00AA6C',
        },
        {
          key: 'maximum_participants',
          title: 'Maximum Participants',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip:
            'Enter the maximum number of participants allowed per round.',
          placeholder: 'eg. 500',
          options: [],
          background: '#0d2dd0',
        },
        {
          key: 'protocol_fee_ratio',
          title: 'Creator Fee (%)',
          inputType: 'number',
          type: 'input',
          icon: '',
          value: '',
          tooltip:
            'Specify the percentage of the fee that will be paid to the creators.',
          placeholder: 'eg. 10',
          options: [],
          background: '#C44127',
        },
      ],
    },
  },
  {
    id: 'white_paper',
    key: 'white_paper',
    title: 'White Paper',
    icon: 'https://storage.googleapis.com/bvm-network/image/ic-whitepaper.svg',
    order: 8,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: '',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Information',
        tooltip: '',
        required: false,
      },
    ],
    baseModuleFields: [
      {
        key: 'token',
        title: 'Token',
        icon: '',
        placableAmount: -1,
        section: 'information',
        preview: false,
        background: '#A041FF',
        fields: [
          {
            key: 'bvm',
            title: 'BVM', // symbol
            value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
        ],
      },
    ],
    baseBlock: {
      key: '',
      title: 'Create a White Paper',
      icon: 'https://storage.googleapis.com/bvm-network/image/ic-whitepaper.svg',
      placableAmount: -1,
      section: '',
      preview: false,
      fields: [
        // {
        //   key: 'download',
        //   title: 'Download',
        //   inputType: '',
        //   type: 'button',
        //   icon: '',
        //   value: '',
        //   tooltip: '',
        //   placeholder: '',
        //   options: [],
        //   background: '#00AA6C',
        // },
      ],
    },
  },
  {
    id: 'wallet_type',
    key: 'wallet_type',
    title: 'Wallet',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
    order: 9,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: '',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Information',
        tooltip: '',
        required: false,
      },
    ],
    baseModuleFields: [
      {
        key: 'wallet_type',
        title: '',
        icon: '',
        placableAmount: 1,
        section: 'information',
        preview: false,
        background: '#A041FF',
        fields: [
          {
            key: 'naka-wallet',
            title: 'Naka wallet', // symbol
            value: WalletType.naka, // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
          {
            key: 'ingame-wallet',
            title: 'InGame wallet', // symbol
            value: WalletType.inGame, // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
        ],
      },
    ],
    baseBlock: {
      key: '',
      title: 'Wallet Type',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
      placableAmount: 1,
      section: '',
      preview: false,
      fields: [],
    },
  },
];
