type Tier = {
  id: string;
  title: string;
  icon: string;
  template: {
    id: string;
    created_at: string;
    updated_at: string;
    key: string;
    title: string;
    required: boolean;
    tooltip: string;
    disable: boolean;
    color: string;
    type: 'module' | 'dropdown';
    value: {
      key: string;
      title: string;
      value: string;
      selectable: boolean;
      tooltip: string;
      priceUSD: number;
      priceBVM: number;
      supportNetwork: '' | 'mainnet' | 'testnet' | 'both';
      icon: string;
    };
  }[];
};

const tierData: Tier[] = [
  {
    id: '0',
    title: 'Basic',
    icon: '/images/lego_tier_1.png',
    template: [
      {
        id: '668f8ebe88f822fe3ebd346e',
        created_at: '2024-07-11T07:50:22.365Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'network',
        title: 'Network',
        required: true,
        tooltip:
          'Select whether you want to create a testnet or deploy a mainnet.',
        color: '#FF7A41',
        type: 'module',
        disable: false,
        value: {
          key: 'mainnet',
          title: 'Mainnet',
          value: 'mainnet',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: '',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd346f',
        created_at: '2024-07-11T07:50:23.442Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'hardware',
        title: 'Hardware',
        required: true,
        tooltip: '',
        color: '#12DAC2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '16g',
          title: '16 GB RAM, 8 cores, 320 GB SSD',
          value: '16g',
          selectable: true,
          priceUSD: 99,
          priceBVM: 160.78928324848457,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3471',
        created_at: '2024-07-11T07:50:23.694Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'compute',
        title: 'Compute',
        required: true,
        tooltip: '',
        color: '#A041FF',
        type: 'module',
        disable: false,
        value: {
          key: 'zk',
          title: 'Zk Rollups',
          value: 'zk',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3472',
        created_at: '2024-07-11T07:50:23.774Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'storage',
        title: 'Storage',
        required: true,
        tooltip:
          'The data of your blockchain is written to a Data Availability layer such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.',
        color: '#15C888',
        type: 'module',
        disable: false,
        value: {
          key: 'polygon',
          title: 'Polygon',
          value: 'polygon',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-polygon.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3474',
        created_at: '2024-07-11T07:50:23.919Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'block_gas_limit',
        title: 'Block Gas Limit',
        required: false,
        tooltip:
          'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
        color: '#FB9F00',
        type: 'dropdown',
        disable: false,
        value: {
          key: '1m',
          title: '1,000,000,000',
          value: '1m',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3475',
        created_at: '2024-07-11T07:50:23.993Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'withdrawal_time',
        title: 'Withdrawal time',
        required: true,
        tooltip:
          'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to Supersonic. This duration primarily depends on the time required for the prover to submit a zk-proof to the verifier contracts deployed on Supersonic.',
        color: '#F200F2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '24h',
          title: '24 hours',
          value: '24h',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
    ],
  },
  {
    id: '1',
    title: 'Standard',
    icon: '/images/lego_tier_2.png',
    template: [
      {
        id: '668f8ebe88f822fe3ebd346e',
        created_at: '2024-07-11T07:50:22.365Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'network',
        title: 'Network',
        required: true,
        tooltip:
          'Select whether you want to create a testnet or deploy a mainnet.',
        color: '#FF7A41',
        type: 'module',
        disable: false,
        value: {
          key: 'mainnet',
          title: 'Mainnet',
          value: 'mainnet',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: '',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd346f',
        created_at: '2024-07-11T07:50:23.442Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'hardware',
        title: 'Hardware',
        required: true,
        tooltip: '',
        color: '#12DAC2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '32g',
          title: '32 GB RAM, 16 cores, 400 GB SSD',
          value: '32g',
          selectable: true,
          priceUSD: 499,
          priceBVM: 810.4429529393313,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3471',
        created_at: '2024-07-11T07:50:23.694Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'compute',
        title: 'Compute',
        required: true,
        tooltip: '',
        color: '#A041FF',
        type: 'module',
        disable: false,
        value: {
          key: 'zk',
          title: 'Zk Rollups',
          value: 'zk',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3472',
        created_at: '2024-07-11T07:50:23.774Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'storage',
        title: 'Storage',
        required: true,
        tooltip:
          'The data of your blockchain is written to a Data Availability layer such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.',
        color: '#15C888',
        type: 'module',
        disable: false,
        value: {
          key: 'polygon',
          title: 'Polygon',
          value: 'polygon',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-polygon.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3474',
        created_at: '2024-07-11T07:50:23.919Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'block_gas_limit',
        title: 'Block Gas Limit',
        required: false,
        tooltip:
          'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
        color: '#FB9F00',
        type: 'dropdown',
        disable: false,
        value: {
          key: '2m',
          title: '2,000,000,000',
          value: '2m',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3475',
        created_at: '2024-07-11T07:50:23.993Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'withdrawal_time',
        title: 'Withdrawal time',
        required: true,
        tooltip:
          'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to Supersonic. This duration primarily depends on the time required for the prover to submit a zk-proof to the verifier contracts deployed on Supersonic.',
        color: '#F200F2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '6h',
          title: '6 hours',
          value: '6h',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
    ],
  },
  {
    id: '2',
    title: 'Advanced',
    icon: '/images/lego_tier_3.png',
    template: [
      {
        id: '668f8ebe88f822fe3ebd346e',
        created_at: '2024-07-11T07:50:22.365Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'network',
        title: 'Network',
        required: true,
        tooltip:
          'Select whether you want to create a testnet or deploy a mainnet.',
        color: '#FF7A41',
        type: 'module',
        disable: false,
        value: {
          key: 'mainnet',
          title: 'Mainnet',
          value: 'mainnet',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: '',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd346f',
        created_at: '2024-07-11T07:50:23.442Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'hardware',
        title: 'Hardware',
        required: true,
        tooltip: '',
        color: '#12DAC2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '64g',
          title: '64 GB RAM, 32 cores, 650 GB SSD',
          value: '64g',
          selectable: true,
          priceUSD: 699,
          priceBVM: 1135.2697877847547,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3470',
        created_at: '2024-07-11T07:50:23.589Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'settlement',
        title: 'Settlement',
        required: false,
        tooltip: '',
        color: '#F8B200',
        type: 'module',
        disable: false,
        value: {
          key: 'bitcoin',
          title: 'Bitcoin',
          value: 'bitcoin',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3471',
        created_at: '2024-07-11T07:50:23.694Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'compute',
        title: 'Compute',
        required: true,
        tooltip: '',
        color: '#A041FF',
        type: 'module',
        disable: false,
        value: {
          key: 'zk',
          title: 'Zk Rollups',
          value: 'zk',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3472',
        created_at: '2024-07-11T07:50:23.774Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'storage',
        title: 'Storage',
        required: true,
        tooltip:
          'The data of your blockchain is written to a Data Availability layer such as Polygon, Celestia, NearDA, Eigen, Filecoin or Avail.',
        color: '#15C888',
        type: 'module',
        disable: false,
        value: {
          key: 'celestia',
          title: 'Celestia',
          value: 'celestia',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-ceslestia.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3473',
        created_at: '2024-07-11T07:50:23.844Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'zk_prover',
        title: 'ZK Prover',
        required: false,
        tooltip: '',
        color: '#15BDC8',
        type: 'module',
        disable: false,
        value: {
          key: 'explorer',
          title: 'Explorer',
          value: 'explorer',
          selectable: true,
          priceUSD: 1300,
          priceBVM: 2111.374426495252,
          tooltip: '',
          supportNetwork: '',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-explorer.svg',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3474',
        created_at: '2024-07-11T07:50:23.919Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'block_gas_limit',
        title: 'Block Gas Limit',
        required: false,
        tooltip:
          'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
        color: '#FB9F00',
        type: 'dropdown',
        disable: false,
        value: {
          key: '4m',
          title: '4,000,000,000',
          value: '4m',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
      {
        id: '668f8ebf88f822fe3ebd3475',
        created_at: '2024-07-11T07:50:23.993Z',
        updated_at: '0001-01-01T00:00:00Z',
        key: 'withdrawal_time',
        title: 'Withdrawal time',
        required: true,
        tooltip:
          'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to Supersonic. This duration primarily depends on the time required for the prover to submit a zk-proof to the verifier contracts deployed on Supersonic.',
        color: '#F200F2',
        type: 'dropdown',
        disable: false,
        value: {
          key: '2h',
          title: '2 hours',
          value: '2h',
          selectable: true,
          priceUSD: 0,
          priceBVM: 0,
          tooltip: '',
          supportNetwork: 'both',
          icon: '',
        },
      },
    ],
  },
];

export default tierData;
