export const ACCOUNT_ABSTRACTION_MOCKUP_DATA: IModelCategory[] = [
  {
    id: '668f8ec088f822fe3ebd3477',
    created_at: '2024-07-11T07:50:24.179Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'input_apps',
    title: 'Account Abstraction',
    required: true,
    tooltip: 'Account Abstraction Tooltip.',
    options: [
      {
        key: 'input_apps_address',
        title: 'Address',
        value: 0,
        valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas.svg',
        logo: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas.svg',
        setupLogo: '',
        needContactUs: false,
        needConfig: false,
        order: 0,
      },
      {
        key: 'input_apps_fee_rate',
        title: 'Fee Rate',
        value: 1,
        valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas.svg',
        logo: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas.svg',
        setupLogo: '',
        needContactUs: false,
        needConfig: false,
        order: 0,
      },
    ],
    color: '#F76649',
    type: 'form',
    disable: false,
    hidden: false,
    multiChoice: true,
    confuseWord: true,
    confuseIcon:
      'https://storage.googleapis.com/bvm-network/icons-tool/icon-bridge-confused.svg',
    confuseTitle: '',
    updatable: true,
    whitelistAddress: null,
    order: 0,
  },
];
