export const mockupData: DappModel[] = [
  {
    id: 'issue-a-token',
    key: 'issue-a-token',
    title: 'Issue a token',
    icon: '/icons-tool/icon-issue-a-token.svg',
    order: 1,
    color: '#FFD700',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    requiredFields: [
      {
        key: 'name',
        title: 'Name',
        type: 'input',
        icon: '',
        value: '',
        defaultValue: '',
        tooltip: '',
      },
      {
        key: 'symbol',
        title: 'Symbol',
        type: 'input',
        icon: '',
        value: '',
        defaultValue: '',
        tooltip: '',
      },
      {
        key: 'total-supply',
        title: 'Total Supply',
        type: 'input',
        icon: '',
        value: '',
        defaultValue: '',
        tooltip: '',
      },
      {
        key: 'blockchain',
        title: 'Blockchain',
        type: 'dropdown',
        icon: '',
        value: 'eth',
        defaultValue: '',
        tooltip: '',
        options: [
          {
            key: 'ethereum',
            title: 'Ethereum',
            type: 'input',
            icon: '',
            value: 'eth',
            defaultValue: '',
            tooltip: '',
          },
          {
            key: 'binance-smart-chain',
            title: 'Binance Smart Chain',
            type: 'input',
            icon: '',
            value: 'bsc',
            defaultValue: '',
            tooltip: '',
          },
        ],
      },
    ],
    optionalFields: [
      {
        key: 'token-allocation',
        title: 'Token Allocation',
        fields: [
          {
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: '',
            value: '',
            defaultValue: '',
            tooltip: '',
          },
          {
            key: 'amount',
            title: 'Amount',
            type: 'input',
            icon: '',
            value: '',
            defaultValue: '',
            tooltip: '',
          },
          {
            key: 'receiver-address',
            title: 'Receiver Address',
            type: 'input',
            icon: '',
            value: '',
            defaultValue: '',
            tooltip: '',
          },
          {
            key: 'vesting',
            title: 'Vesting',
            type: 'extends',
            icon: '',
            defaultValue: '',
            value: 0,
            tooltip: '',
            options: [
              {
                key: 'accelerated-vesting',
                title: 'Accelerated Vesting',
                type: 'input',
                icon: '',
                value: '',
                defaultValue: '',
                tooltip: '',
              },
              {
                key: 'linear-vesting',
                title: 'Linear Vesting',
                type: 'input',
                icon: '',
                value: '',
                defaultValue: '',
                tooltip: '',
              },
            ],
          },
        ],
      },
    ],
  },
];
