export const mockupData: DappModel[] = [
  {
    id: 'class',
    key: 'class',
    title: 'Class',
    icon: '/icons-tool/icon-issue-a-token.svg',
    order: 1,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    requiredFields: [
      {
        key: 'name',
        title: 'Name',
        type: 'input',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        value: '',
        tooltip: '',
      },
      {
        key: 'subject',
        title: 'Subject',
        type: 'dropdown',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        value: 'math',
        tooltip: '',
        options: [
          {
            key: 'math',
            title: 'Math',
            value: 'math',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            tooltip: '',
            type: '',
            options: [],
          },
          {
            key: 'english',
            title: 'English',
            value: 'english',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            tooltip: '',
            type: '',
            options: [],
          },
        ],
      },
    ],
    optionalFields: [
      {
        key: 'student',
        title: 'Student',
        fields: [
          {
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
          },
          {
            key: 'details',
            title: 'Details',
            type: 'extends',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: 0,
            tooltip: '',
            options: [
              {
                key: 'age',
                title: 'Age',
                value: '18',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'input',
                options: [],
              },
              {
                key: 'address',
                title: 'Address',
                value: '',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'input',
                options: [],
              },
              {
                key: 'main-color',
                title: 'Main color',
                value: 'blue',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'dropdown',
                options: [
                  {
                    key: 'blue',
                    title: 'Blue',
                    value: 'blue',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: '',
                    options: [],
                  },
                  {
                    key: 'red',
                    title: 'Red',
                    value: 'red',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: '',
                    options: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
