export const dappMockupData: DappModel[] = [
  {
    id: 'token_generation',
    key: 'token_generation',
    title: 'Token Generation',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 1,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    baseBlock: {
      key: 'token_generation',
      title: 'Token Generation',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      placableAmount: -1,
      fields: [
        {
          key: 'token_name',
          title: 'Token Name',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'token_symbol',
          title: 'Symbol',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'token_supply',
          title: 'Total Supply',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
      ],
    },
    blockFields: [
      {
        key: 'tokenomics',
        title: 'Tokenomics',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        placableAmount: -1,
        fields: [
          {
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'amount',
            title: 'Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'address',
            title: 'Receiver Address',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'vesting',
            title: 'Vesting?',
            type: 'extends',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: 0,
            tooltip: '',
            options: [
              {
                key: 'cliff',
                title: 'Cliff',
                value: '',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'cliff_value',
                    title: 'Time',
                    value: 'day',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'dropdown',
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: 'day',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: 'week',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: 'month',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'cliff_amount',
                    title: 'Amount',
                    value: '',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
              {
                key: 'duration',
                title: 'Duration',
                value: '',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'timeDuration',
                    title: 'Time',
                    value: 'day',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'dropdown',
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: 'day',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: 'week',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: 'month',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'amountDuration',
                    title: 'Amount',
                    value: '',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
              // {
              //   key: 'amount',
              //   title: 'Amount',
              //   value: '',
              //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //   tooltip: '',
              //   type: 'input',
              //   options: [],
              // },
              // {
              //   key: 'marks',
              //   title: 'Marks',
              //   value: 0,
              //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //   tooltip: '',
              //   type: 'extends',
              //   options: [
              //     {
              //       key: 'math',
              //       title: 'Math',
              //       value: '',
              //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //       tooltip: '',
              //       type: 'input',
              //       options: [],
              //     },
              //     {
              //       key: 'english',
              //       title: 'English',
              //       value: '',
              //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //       tooltip: '',
              //       type: 'input',
              //       options: [],
              //     },
              //   ],
              // },
            ],
          },
        ],
      },
    ],
    singleFields: [
      {
        key: 'color',
        title: 'Color',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        placableAmount: -1,
        fields: [
          {
            key: 'color',
            title: 'Color',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
        ],
      },
    ],
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    baseBlock: {
      key: 'class',
      title: 'Create a Staking Pool',
      icon: '',
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: 'math',
          tooltip: '',
          options: [
            {
              key: 'eth',
              title: 'ETH', // symbol
              value: '0x1234', // contract_address
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: 'math',
          tooltip: '',
          options: [
            {
              key: 'eth',
              title: 'ETH', // symbol
              value: '0x1234', // contract_address
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
      ],
    },
  },
];
