export const dappMockupData: DappModel[] = [
  {
    id: 'token_generation',
    key: 'token_generation',
    title: 'Token Generation',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 1,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Information',
        tooltip: 'Token Generation information',
        required: true,
      },
      {
        key: 'tokenomics',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Tokenomics',
        tooltip: 'Token Generation tokenomics',
        required: false,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Token Information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      placableAmount: -1,
      section: 'information',
      fields: [
        {
          key: 'token_name',
          title: 'Token Name',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'token_symbol',
          title: 'Symbol',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'token_supply',
          title: 'Total Supply',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
      ],
    },
    blockFields: [
      {
        key: 'allocation',
        title: 'Allocation',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        placableAmount: -1,
        section: 'tokenomics',
        fields: [
          {
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'total_amount',
            title: 'Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'address',
            title: 'Receiver Address',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'is_vesting',
            title: 'Vesting?',
            type: 'extends',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: 0,
            tooltip: '',
            options: [
              {
                key: 'cliff',
                title: 'Cliff',
                value: '',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'cliff_unit',
                    title: 'Time',
                    value: '0',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'dropdown',
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'cliff',
                    title: 'Amount',
                    value: '',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
              {
                key: 'duration',
                title: 'Duration',
                value: '',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'duration_unit',
                    title: 'Time',
                    value: '0',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'dropdown',
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'duration',
                    title: 'Amount',
                    value: '',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
              // {
              //   key: 'amount',
              //   title: 'Amount',
              //   value: '',
              //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //   tooltip: '',
              //   type: 'input',
              //   options: [],
              // },
              // {
              //   key: 'marks',
              //   title: 'Marks',
              //   value: 0,
              //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //   tooltip: '',
              //   type: 'extends',
              //   options: [
              //     {
              //       key: 'math',
              //       title: 'Math',
              //       value: '',
              //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //       tooltip: '',
              //       type: 'input',
              //       options: [],
              //     },
              //     {
              //       key: 'english',
              //       title: 'English',
              //       value: '',
              //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //       tooltip: '',
              //       type: 'input',
              //       options: [],
              //     },
              //   ],
              // },
            ],
          },
        ],
      },
    ],
    // singleFields: [
    //   {
    //     key: 'color',
    //     title: 'Color',
    //     icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //     placableAmount: -1,
    //     fields: [
    //       {
    //         key: 'color',
    //         title: 'Color',
    //         type: 'input',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '',
    //         tooltip: '',
    //         options: [],
    //       },
    //     ],
    //   },
    // ],
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Information',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'class',
      title: 'Create a Staking Pool',
      icon: '',
      placableAmount: -1,
      section: 'information',
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: 'math',
          tooltip: '',
          options: [
            {
              key: 'eth',
              title: 'ETH', // symbol
              value: '0x1234', // contract_address
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: 'math',
          tooltip: '',
          options: [
            {
              key: 'eth',
              title: 'ETH', // symbol
              value: '0x1234', // contract_address
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'airdrop',
    key: 'airdrop',
    title: 'Airdrop',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Information',
        tooltip: '',
        required: true,
      },
      {
        key: 'actions',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Actions',
        tooltip: '',
        required: false,
      },
    ],
    baseBlock: {
      key: 'class',
      title: 'Token for Airdrop',
      icon: '',
      placableAmount: -1,
      section: 'information',
      fields: [
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: 'math',
          tooltip: '',
          options: [
            {
              key: 'eth',
              title: 'ETH', // symbol
              value: '0x1234', // contract_address
              icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'airdrop_amount',
          title: 'Amount',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
      ],
    },
    blockFields: [
      {
        key: 'airdrop_staking',
        title: 'For staking',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        placableAmount: -1,
        section: 'actions',
        fields: [
          {
            key: 'token',
            title: 'Token',
            type: 'dropdown',
            icon: '',
            value: 'token',
            tooltip: '',
            options: [
              {
                key: 'eth',
                title: 'ETH', // symbol
                value: '0x1234', // contract_address
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
                tooltip: '',
                type: '',
                options: [],
              },
            ],
          },
          {
            key: 'required_amount',
            title: 'Require Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'reward_amount',
            title: 'Reward Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
        ],
      },
      {
        key: 'airdrop_holding',
        title: 'For holding',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        placableAmount: -1,
        section: 'actions',
        fields: [
          {
            key: 'token',
            title: 'Token',
            type: 'dropdown',
            icon: '',
            value: 'token',
            tooltip: '',
            options: [
              {
                key: 'eth',
                title: 'ETH', // symbol
                value: '0x1234', // contract_address
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
                tooltip: '',
                type: '',
                options: [],
              },
            ],
          },
          {
            key: 'required_amount',
            title: 'Require Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'reward_amount',
            title: 'Reward Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
        ],
      },
      {
        key: 'airdrop_tasks',
        title: 'For tasks',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        placableAmount: -1,
        section: 'actions',
        fields: [
          {
            key: 'task',
            title: 'Task',
            type: 'dropdown',
            icon: '',
            value: 'task',
            tooltip: '',
            options: [
              {
                key: 'refer',
                title: 'Refer a friend to join IDO', // symbol
                value: 'refer', // contract_address
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
                tooltip:
                  'Spread the love to your friends, team, and communities.',
                type: '',
                options: [],
              },
              {
                key: 'spread_on_x',
                title: 'Publish a tweet mentioning', // symbol
                value: 'spread_on_x', // contract_address
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
                tooltip: 'Publish a tweet mentioning',
                type: '',
                options: [],
              },
              {
                key: 'like_on_x',
                title: `Like and retweet Twitter' pinned tweet`, // symbol
                value: 'like_on_x', // contract_address
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
                tooltip: `Like and retweet Twitter' pinned tweet`,
                type: '',
                options: [],
              },
            ],
          },
          {
            key: 'reward_amount',
            title: 'Reward Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
        ],
      },
    ],
  },
];

// <baseIndex>-<type>-<fieldKey>-<level>-<index>-<blockKey>
export const dappTemplateFormMockupData = {
  dappKey: 'token_generation',
  fieldValue: {
    '0-base-token_name-0': 'BVM',
    '0-base-token_supply-0': '1000000000',
    '0-base-token_symbol-0': 'BVM',
    '0-block-vesting-0-0-allocation': true,
    '0-block-address-0-0-allocation': '0x1234',
    '0-block-amount-0-0-allocation': '1000000',
    '0-block-cliff_value-1-0-allocation': 'day',
    '0-block-cliff_amount-1-0-allocation': '30',
    '0-block-duration_value-1-0-allocation': 'day',
    '0-block-duration_amount-1-0-allocation': '90',

    '1-base-token_name-0': 'Meta',
    '1-base-token_supply-0': '1000000000',
    '1-base-token_symbol-0': 'META',
    '1-block-address-0-0-allocation': '0x1234',
    '1-block-amount-0-0-allocation': '1000000',
    '1-block-vesting-0-0-allocation': false,
  },
};
