export const dappMockupData: DappModel[] = [
  {
    id: 'class',
    key: 'class',
    title: 'Class',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 1,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    baseBlock: {
      key: 'class',
      title: 'Token Generation',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      fields: [
        {
          key: 'name',
          title: 'Token Name',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'symbol',
          title: 'Symbol',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'total_supply',
          title: 'Total Supply',
          type: 'input',
          icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          value: '',
          tooltip: '',
          options: [],
        },
        // {
        //   key: 'subject',
        //   title: 'Subject',
        //   type: 'dropdown',
        //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        //   value: 'math',
        //   tooltip: '',
        //   options: [
        //     {
        //       key: 'math',
        //       title: 'Math',
        //       value: 'math',
        //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        //       tooltip: '',
        //       type: '',
        //       options: [],
        //     },
        //     {
        //       key: 'english',
        //       title: 'English',
        //       value: 'english',
        //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        //       tooltip: '',
        //       type: '',
        //       options: [],
        //     },
        //   ],
        // },
      ],
    },
    blockFields: [
      {
        key: 'tokenomics',
        title: 'Tokenomics',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        fields: [
          {
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'amount',
            title: 'Amount',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'receiver_address',
            title: 'Receiver Address',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
          // {
          //   key: 'main_color',
          //   title: 'Main color',
          //   value: 'blue',
          //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          //   tooltip: '',
          //   type: 'dropdown',
          //   options: [
          //     {
          //       key: 'blue',
          //       title: 'Blue',
          //       value: 'blue',
          //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          //       tooltip: '',
          //       type: '',
          //       options: [],
          //     },
          //     {
          //       key: 'red',
          //       title: 'Red',
          //       value: 'red',
          //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
          //       tooltip: '',
          //       type: '',
          //       options: [],
          //     },
          //   ],
          // },
          {
            key: 'vesting',
            title: 'Vesting?',
            type: 'extends',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: 0,
            tooltip: '',
            options: [
              {
                key: 'cliff',
                title: 'Cliff',
                value: '',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'timeCiff',
                    title: 'Time Cliff',
                    value: 'day',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'group',
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: 'day',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: 'week',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: 'month',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'amount',
                    title: 'Amount',
                    value: '',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
              // {
              //   key: 'amount',
              //   title: 'Amount',
              //   value: '',
              //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //   tooltip: '',
              //   type: 'input',
              //   options: [],
              // },
              {
                key: 'duration',
                title: 'Duration',
                value: '',
                icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                tooltip: '',
                type: 'dropdown',
                options: [
                  {
                    key: 'timeCiff',
                    title: 'Time Cliff',
                    value: 'day',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'group',
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: 'day',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: 'week',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: 'month',
                        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'amount',
                    title: 'Amount',
                    value: '',
                    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
              // {
              //   key: 'amount',
              //   title: 'Amount',
              //   value: '',
              //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //   tooltip: '',
              //   type: 'input',
              //   options: [],
              // },
              // {
              //   key: 'marks',
              //   title: 'Marks',
              //   value: 0,
              //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //   tooltip: '',
              //   type: 'extends',
              //   options: [
              //     {
              //       key: 'math',
              //       title: 'Math',
              //       value: '',
              //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //       tooltip: '',
              //       type: 'input',
              //       options: [],
              //     },
              //     {
              //       key: 'english',
              //       title: 'English',
              //       value: '',
              //       icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
              //       tooltip: '',
              //       type: 'input',
              //       options: [],
              //     },
              //   ],
              // },
            ],
          },
        ],
      },
    ],
    singleFields: [
      {
        key: 'color',
        title: 'Color',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        fields: [
          {
            key: 'color',
            title: 'Color',
            type: 'input',
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
            value: '',
            tooltip: '',
            options: [],
          },
        ],
      },
    ],
  },
];

export const modelCategoriesMockupData: IModelCategory[] = [
  {
    id: '668f8ebe88f822fe3ebd346e',
    created_at: '2024-07-11T07:50:22.365Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'network',
    title: 'Networks',
    required: true,
    tooltip:
      'Choose whether to test on the testnet for trials and development or deploy on the mainnet for production and live use.',
    options: [
      {
        key: 'mainnet',
        title: 'Mainnet',
        value: 1,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: '',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-mainnet.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'testnet',
        title: 'Testnet',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: '',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-testnet.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#FF7A41',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 1,
  },
  {
    id: '668f8ebf88f822fe3ebd346f',
    created_at: '2024-07-11T07:50:23.442Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'hardware',
    title: 'Hardware',
    required: true,
    tooltip:
      'Select your hardware configuration to match the specific needs of your blockchain. Consider factors such as RAM, CPU cores, and storage capacity to ensure optimal performance and scalability.',
    options: [
      {
        key: '16g',
        title: '16 GB RAM, 8 cores, 320 GB SSD',
        value: 16785728,
        // valueStr: '1',
        selectable: true,
        priceUSD: 99,
        priceBVM: 138.78076090892333,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '32g',
        title: '32 GB RAM, 16 cores, 400 GB SSD',
        value: 33571216,
        // valueStr: '2',
        selectable: true,
        priceUSD: 499,
        priceBVM: 699.5111080156842,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '64g',
        title: '64 GB RAM, 32 cores, 650 GB SSD',
        value: 67142282,
        // valueStr: '3',
        selectable: true,
        priceUSD: 699,
        priceBVM: 979.8762815690646,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-hardware.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#12DAC2',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 2,
  },
  {
    id: '668f8ebf88f822fe3ebd3470',
    created_at: '2024-07-11T07:50:23.589Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'settlement',
    title: 'Layer 1',
    required: true,
    tooltip:
      'Select the base layer on which you want to build your blockchain. This will determine the base protocol and network characteristics, such as security, scalability, and consensus mechanisms.',
    options: [
      {
        key: 'bitcoin',
        title: 'Bitcoin',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'ethereum',
        title: 'Ethereum',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#F8B200',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'L1',
    // whitelistAddress: null,
    order: 0,
  },
  {
    id: '668f8ebf88f822fe3ebd3471',
    created_at: '2024-07-11T07:50:23.694Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'compute',
    title: 'Rollups',
    required: true,
    tooltip:
      'Choose the scaling solution tailored to your needs. Rollups enhance scalability and reduce transaction costs by processing transactions off-chain while posting transaction data on-chain.',
    options: [
      {
        key: 'zk',
        title: 'ZK Rollup',
        value: 21,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip:
          'Offer even higher scalability and cost-efficiency by bundling many transactions into a single proof. Provide strong security through zero-knowledge proofs, enabling fast finality and enhanced privacy. Can be done automatically.',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'op',
        title: 'Optimistic Rollup',
        value: 20,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip:
          'Significantly increase transaction throughput and reduce costs. EVM-compatible and secure. <b>Need to contact the team to deploy</b>.',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-op.svg',
        // logo: '',
        needContactUs: true,
        order: 0,
      },
      {
        key: 'gpu',
        title: 'GPU Rollup',
        value: 22,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#A041FF',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 3,
  },
  {
    id: '668f8ebf88f822fe3ebd3472',
    created_at: '2024-07-11T07:50:23.774Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'storage',
    title: 'Data Availability',
    required: true,
    tooltip:
      'Ensure easy access to transaction details and smart contracts for all nodes on L1, L2, and even L3 networks. Using a separate DA layer reduces mainnet congestion, enhancing scalability, security, and transaction cost-efficiency.',
    options: [
      {
        key: 'bvm_da',
        title: 'BVM',
        value: 21,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-bvm.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'polygon',
        title: 'Polygon',
        value: 10,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-polygon.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'celestia',
        title: 'Celestia',
        value: 13,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-ceslestia.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'avail',
        title: 'Avail',
        value: 18,
        // valueStr: '',
        selectable: true,
        priceUSD: 10,
        priceBVM: 14.018258677669023,
        tooltip: '',
        supportNetwork: 'testnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-avail.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'filecoin',
        title: 'Filecoin',
        value: 21,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-filecoin.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'near_da',
        title: 'Near',
        value: 15,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-near.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#15C888',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'DA',
    // whitelistAddress: null,
    order: 4,
  },
  {
    id: '668f8ebf88f822fe3ebd3473',
    created_at: '2024-07-11T07:50:23.844Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'zk_prover',
    title: 'Prover',
    required: false,
    tooltip:
      "Prover is a crucial component responsible for generating cryptographic proofs that verify the correctness of transactions processed off-chain by the blockchain's sequencer.",
    options: [
      {
        key: 'zk_prover',
        title: 'ZK Prover',
        value: 1,
        // valueStr: '',
        selectable: true,
        priceUSD: 1300,
        priceBVM: 1822.3736280969729,
        tooltip: '',
        supportNetwork: '',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-zk.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#15BDC8',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 7,
  },
  {
    id: '668f8ebf88f822fe3ebd3474',
    created_at: '2024-07-11T07:50:23.919Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'block_gas_limit',
    title: 'Gas',
    required: true,
    tooltip:
      'The block gas limit defines the maximum amount of gas that all transactions in a single block can consume.',
    options: [
      {
        key: '1m',
        title: '1,000,000,000',
        value: 1000000000,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-min.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '2m',
        title: '2,000,000,000',
        value: 2000000000,
        // valueStr: '',
        selectable: true,
        priceUSD: 5,
        priceBVM: 7.009129338834511,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-medium.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '4m',
        title: '4,000,000,000',
        value: 4000000000,
        // valueStr: '',
        selectable: true,
        priceUSD: 10,
        priceBVM: 14.018258677669023,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-gas-max.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#FB9F00',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'Block Gas Limit',
    // whitelistAddress: null,
    order: 5,
  },
  {
    id: '668f8ebf88f822fe3ebd3475',
    created_at: '2024-07-11T07:50:23.993Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'withdrawal_time',
    title: 'Withdrawals',
    required: true,
    tooltip:
      'The withdrawal period is the time frame during which your users can withdraw their assets from your blockchain back to the L1.',
    options: [
      {
        key: '12h',
        title: '12-hour',
        value: 43200,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-slow.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '4h',
        title: '4-hour',
        value: 14400,
        // valueStr: '',
        selectable: true,
        priceUSD: 5,
        priceBVM: 7.009129338834511,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-fast.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: '2h',
        title: '2-hour',
        value: 7200,
        // valueStr: '',
        selectable: true,
        priceUSD: 10,
        priceBVM: 14.018258677669023,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-time-superfast.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#F200F2',
    type: 'module',
    disable: false,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'Withdrawal Time',
    // whitelistAddress: null,
    order: 6,
  },
  {
    id: '668f8ec088f822fe3ebd3476',
    created_at: '2024-07-11T07:50:24.072Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'wallet',
    title: 'UX',
    required: false,
    tooltip:
      'This module enhances user experience by allowing gas fees to be paid in different cryptocurrencies, eliminating the need to hold a specific one for transaction fees.',
    options: [
      {
        key: 'flex_pay',
        title: 'Account Abstraction',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#00C1CD',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: true,
    confuseIcon: '',
    confuseTitle: 'Wallet',
    // whitelistAddress: null,
    order: 8,
  },
  {
    id: '668f8ec088f822fe3ebd3477',
    created_at: '2024-07-11T07:50:24.179Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'bridge_apps',
    title: 'Bridges',
    required: false,
    tooltip:
      'Bring BTC, ETH, and other assets to your blockchain and transfer them back to Bitcoin and Ethereum networks.',
    options: [
      {
        key: 'btc_bridge',
        title: 'Bitcoin',
        value: 0,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-btc.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/btc_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'eth_bridge',
        title: 'Ethereum',
        value: 1,
        // valueStr: '',
        selectable: true,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/eth_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'solana_bridge',
        title: 'Solana',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-solana.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/solana_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'runes_bridge',
        title: 'Runes',
        value: 3,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-runes.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/runs_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'ordinals_bridge',
        title: 'Ordinals',
        value: 4,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'mainnet',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-ordinals.svg',
        // logo: 'https://storage.googleapis.com/bvm-network/image/ordinals_bridge_ic.png',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#855AFF',
    type: 'module',
    disable: false,
    multiChoice: true,
    confuseWord: true,
    confuseIcon:
      'https://storage.googleapis.com/bvm-network/icons-tool/icon-bridge-confused.svg',
    confuseTitle: 'Your chain',
    // whitelistAddress: null,
    order: 9,
  },
  {
    id: '668f8ec088f822fe3ebd3478',
    created_at: '2024-07-11T07:50:24.299Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'defi_apps',
    title: 'DeFi',
    required: false,
    tooltip:
      'Pre-install DeFi dapps to your blockchain, including token issuance, DEX, staking, and more to boost liquidity and attract users with essential financial services from the start.',
    options: [
      {
        key: 'issue_token',
        title: 'Issue a token',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'vesting',
        title: 'Vesting',
        value: 1,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-vesting.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'staking',
        title: 'Staking',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-staking.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'dex',
        title: 'DEX',
        value: 3,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-dex.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'orderbook',
        title: 'Orderbook',
        value: 4,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'perpeptual',
        title: 'Perpeptual',
        value: 5,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-perceptual.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#F76649',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 10,
  },
  {
    id: '668f8ec088f822fe3ebd3479',
    created_at: '2024-07-11T07:50:24.462Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'degen_apps',
    title: 'Degens',
    required: false,
    tooltip:
      'Pre-install degen dapps to your blockchain to attract attention and increase user engagement.',
    options: [
      {
        key: 'yolo',
        title: 'YOLO',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-yolo.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'nft_raffle',
        title: 'NFT Raffle',
        value: 1,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-raffle.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'mr_market',
        title: 'Mr. Markets',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-bull-bear.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#E6004D',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: null,
    order: 11,
  },
  {
    id: '668f8ec088f822fe3ebd347a',
    created_at: '2024-07-11T07:50:24.535Z',
    updated_at: '0001-01-01T00:00:00Z',
    key: 'gaming_apps',
    title: 'Games',
    required: false,
    tooltip:
      'Pre-install gaming dapps for a fun and immersive experience. Introduce users to new and exciting on-chain games.',
    options: [
      {
        key: 'pepe_fight',
        title: 'Pepe Fight',
        value: 0,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'merge',
        title: 'Merge',
        value: 1,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'blast',
        title: 'Blast',
        value: 2,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
      {
        key: 'connect',
        title: 'Connect',
        value: 3,
        // valueStr: '',
        selectable: false,
        priceUSD: 0,
        priceBVM: 0,
        tooltip: '',
        supportNetwork: 'both',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-game.svg',
        // logo: '',
        needContactUs: false,
        order: 0,
      },
    ],
    color: '#C000E6',
    type: 'module',
    disable: true,
    multiChoice: false,
    confuseWord: false,
    confuseIcon: '',
    confuseTitle: '',
    // whitelistAddress: [
    //   '0x2d66881F48Fe18c63C0CB52b3559FBf520287b2F',
    //   '0xb262df097f649cb962b6ee256b19eec51d77cfa8',
    // ],
    order: 12,
  },
];
