export const dappMockupData: DappModel[] = [
  {
    id: 'token_generation',
    key: 'token_generation',
    title: 'Token Generation',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
    order: 1,
    color: '#F76649',
    color_border: '#A041FF',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: 'new',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: 'Information',
        tooltip: 'Token Generation information',
        required: true,
      },
      {
        key: 'tokenomics',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
        title: 'Tokenomics',
        tooltip: 'Token Generation tokenomics',
        required: false,
      },
      // {
      //   key: 'base_modules',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Base Modules',
      //   tooltip: 'Token module',
      //   required: false,
      // },
      // {
      //   key: 'modules',
      //   icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
      //   title: 'Modules',
      //   tooltip: 'Token module',
      //   required: false,
      // },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Token Information',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      background: '#00AA6C',
      fields: [
        {
          background: '#00AA6C',
          key: 'token_name',
          title: 'Token Name',
          previewTitle: 'Name',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          background: '#00AA6C',
          key: 'token_symbol',
          title: 'Symbol',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          background: '#00AA6C',
          key: 'token_supply',
          title: 'Total Supply',
          previewTitle: 'Supply',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          background: '#00AA6C',
          key: 'receiver_address',
          title: 'Receiver Address',
          previewTitle: 'Address',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
      ],
    },
    blockFields: [
      {
        key: 'allocation',
        title: 'Allocation',
        icon: '/icons-tool/issue-a-token/icon-allocation.svg',
        placableAmount: -1,
        section: 'tokenomics',
        preview: true,
        background: '#F8B200',
        fields: [
          {
            background: '#F8B200',
            key: 'name',
            title: 'Name',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            background: '#F8B200',
            key: 'total_amount',
            title: 'Amount',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            background: '#F8B200',
            key: 'address',
            title: 'Receiver Address',
            previewTitle: 'Address',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            options: [],
          },
          {
            key: 'is_vesting',
            title: 'Vesting?',
            type: 'extends',
            icon: '',
            value: 0,
            tooltip: '',
            options: [
              {
                key: 'cliff',
                title: 'Cliff',
                value: '',
                icon: '',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'cliff_unit',
                    title: 'Time',
                    value: '0',
                    icon: '',
                    tooltip: '',
                    type: 'dropdown',
                    level: 1,
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'cliff',
                    title: 'Amount',
                    level: 1,
                    value: '',
                    icon: '',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
              {
                key: 'duration',
                title: 'Duration',
                value: '',
                icon: '',
                tooltip: '',
                type: 'group',
                options: [
                  {
                    key: 'duration_unit',
                    title: 'Time',
                    value: '0',
                    icon: '',
                    tooltip: '',
                    type: 'dropdown',
                    level: 1,
                    options: [
                      {
                        key: 'day',
                        title: 'Day',
                        value: '0',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'week',
                        title: 'Week',
                        value: '1',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                      {
                        key: 'month',
                        title: 'Month',
                        value: '2',
                        icon: '',
                        tooltip: '',
                        type: '',
                        options: [],
                      },
                    ],
                  },
                  {
                    key: 'duration',
                    title: 'Amount',
                    level: 1,
                    value: '',
                    icon: '',
                    tooltip: '',
                    type: 'input',
                    options: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    // moduleFields: [
    //   {
    //     preview: false,
    //     key: 'number_module',
    //     title: 'Number',
    //     icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //     placableAmount: -1,
    //     section: 'modules',
    //     fields: [
    //       {
    //         key: '1',
    //         title: 'Number 1',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '1',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '2',
    //         title: 'Number 2',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '2',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '3',
    //         title: 'Number 3',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '3',
    //         tooltip: '',
    //         options: [],
    //       },
    //     ],
    //   },
    // ],
    // baseModuleFields: [
    //   {
    //     preview: false,
    //     key: 'number_module',
    //     title: 'Number',
    //     icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //     placableAmount: -1,
    //     section: 'base_modules',
    //     fields: [
    //       {
    //         key: '1',
    //         title: 'Number 1',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '1',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '2',
    //         title: 'Number 2',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '2',
    //         tooltip: '',
    //         options: [],
    //       },
    //       {
    //         key: '3',
    //         title: 'Number 3',
    //         type: '',
    //         icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    //         value: '3',
    //         tooltip: '',
    //         options: [],
    //       },
    //     ],
    //   },
    // ],
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-staking.svg',
    order: 2,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'New',
      color: '#000',
      background: '#00AA6C',
      status: '',
    },
    sections: [
      {
        key: 'staking_token',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Token',
        tooltip: '',
        required: true,
      },
      {
        key: 'reward_token',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Reward Token',
        tooltip: '',
        required: true,
      },
      {
        key: 'info',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Reward Rate',
        tooltip: '',
        required: true,
      },
    ],
    baseModuleFields: [
      {
        key: 'staking_token',
        title: 'Staking Token',
        icon: '',
        placableAmount: -1,
        section: 'staking_token',
        preview: true,
        background: '#A041FF',
        fields: [
          {
            key: 'bvm',
            title: 'BVM', // symbol
            value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
          {
            key: 'eth',
            title: 'ETH (Upgrade plan 99$)', // symbol
            value: '0x1234', // contract_address
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: false,
          },
        ],
      },
    ],
    moduleFields: [
      {
        key: 'reward_token',
        title: 'Reward Token',
        icon: '',
        preview: true,
        placableAmount: 1,
        section: 'reward_token',
        background: '#15C888',
        fields: [
          {
            key: 'bvm',
            title: 'BVM', // symbol
            value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222', // contract_address
            icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: true,
          },
          {
            key: 'eth',
            title: 'ETH (Upgrade plan 99$)', // symbol
            value: '0x1234', // contract_address
            icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg', // image_url
            tooltip: '',
            type: '',
            options: [],
            selectable: false,
          },
        ],
      },
    ],
    blockFields: [
      {
        key: 'info',
        title: 'Reward rate',
        icon: '',
        placableAmount: 1,
        section: 'info',
        preview: true,
        background: '#F8B200',
        fields: [
          {
            key: 'rate',
            title: 'Rate',
            type: 'input',
            icon: '',
            value: '',
            tooltip: 'Exchange rate between staking token and reward token.',
            placeholder: 'eg. 1',
            options: [],
            background: '#F8B200',
          },
          {
            key: 'apr',
            title: 'APR',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            placeholder: 'eg. 20%',
            options: [],
            background: '#F8B200',
          },
          {
            key: 'amount',
            title: 'Reward amount',
            previewTitle: 'Reward',
            type: 'input',
            icon: '',
            value: '',
            tooltip: '',
            placeholder: 'eg. 100,000',
            options: [],
            background: '#F8B200',
          },
        ],
      },
    ],
    baseBlock: {
      key: '',
      title: 'Create a Staking Pool',
      icon: '',
      placableAmount: -1,
      section: '',
      preview: true,
      fields: [],
    },
  },
  {
    id: 'airdrop',
    key: 'airdrop',
    title: 'Airdrop',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
    order: 3,
    color: '#F76649',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Information',
        tooltip: '',
        required: true,
      },
      {
        key: 'actions',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Actions',
        tooltip: '',
        required: false,
      },
    ],
    baseBlock: {
      preview: true,
      key: 'class',
      title: 'Token for Airdrop',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-orderbook.svg',
      placableAmount: -1,
      section: 'information',
      fields: [
        {
          key: 'airdrop_title',
          title: 'Title',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
        {
          key: 'airdrop_amount',
          title: 'Amount',
          type: 'input',
          icon: '',
          value: '',
          tooltip: '',
          options: [],
        },
      ],
    },
    blockFields: [
      {
        key: 'airdrop_tasks',
        title: 'For tasks',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        placableAmount: -1,
        section: 'actions',
        preview: true,
        fields: [
          {
            key: 'task',
            title: 'Task',
            type: 'dropdown',
            icon: '',
            value: 'task',
            tooltip: '',
            options: [],
          },
          // {
          //   key: 'reward_amount',
          //   title: 'Reward Amount',
          //   type: 'input',
          //   icon: '',
          //   value: '',
          //   tooltip: '',
          //   options: [],
          // },
        ],
      },
    ],
  },
];

// <baseIndex>-<type>-<fieldKey>-<level>-<index>-<blockKey>
export const dappTemplateFormMockupData = {
  dappKey: 'token_generation',
  fieldValue: {
    '0-base-token_name-0': 'BVM',
    '0-base-token_symbol-0': 'BVM',
    '0-base-token_supply-0': '1000000000',
    '0-block-name-0-0-allocation': 'Airdrop',
    '0-block-total_amount-0-0-allocation': '300000',
    '0-block-address-0-0-allocation': '0x1234',
    '0-block-is_vesting-0-0-allocation': true,
    '0-block-cliff_unit-1-0-allocation': '0',
    '0-block-cliff-1-0-allocation': '10',
    '0-block-duration_unit-1-0-allocation': '1',
    '0-block-duration-1-0-allocation': '10',

    '1-base-token_name-0': 'Meme',
    '1-base-token_symbol-0': 'MEM',
    '1-base-token_supply-0': '100000000000000',
    '1-block-name-0-0-allocation': 'Airdrop',
    '1-block-total_amount-0-0-allocation': '100000000000000',
    '1-block-address-0-0-allocation': '0x1231',
    '1-block-is_vesting-0-0-allocation': false,
  },
};

export const stakingTemplateFormMockupData = [
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'Stopped',
      color: '#000',
      background: '#00AA6C',
      status: 'stopped',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '12%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    label: {
      title: 'Stopped',
      color: '',
      background: '',
      status: 'stopped',
    },
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '50%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '23%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Stopped',
      color: '#bdbdbd',
      background: '#212d28',
      // color: '',
      // background: '',
      status: 'stopped',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '25%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '10%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
          tooltip: '',
          options: [
            {
              key: 'BVM',
              title: 'BVM',
              value: '0x08b4e0434c42d9bfeeba468324ee5e2a23cd4222',
              icon: 'https://cdn.bvm.network/internal/8c50c936-cb41-40d0-8d93-8cdf7f88bd37.svg',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '25%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
  {
    id: 'staking',
    key: 'staking',
    title: 'Staking',
    icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
    order: 2,
    color: '#24704D',
    label: {
      title: 'Processing',
      color: '',
      background: '',
      status: 'processing',
    },
    created_at: '2021-09-14T09:00:00.000Z',
    updated_at: '2021-09-14T09:00:00.000Z',
    tooltip: '',
    sections: [
      {
        key: 'information',
        icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-eth.svg',
        title: 'Staking Pool',
        tooltip: '',
        required: true,
      },
    ],
    baseBlock: {
      key: 'token_info',
      title: 'Staking Pool',
      icon: 'https://storage.googleapis.com/bvm-network/icons-tool/icon-issue-a-token.svg',
      placableAmount: -1,
      section: 'information',
      preview: true,
      fields: [
        {
          key: 'staking_token',
          title: 'Staking Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'reward_token',
          title: 'Reward Token',
          type: 'dropdown',
          icon: '',
          value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
          tooltip: '',
          options: [
            {
              key: '',
              title: '',
              value: '0x28390a0e33768da0e3803fb86dc632014be424f4',
              icon: '',
              tooltip: '',
              type: '',
              options: [],
            },
          ],
        },
        {
          key: 'rate',
          title: 'Rate',
          type: 'input',
          icon: '',
          value: '1',
          tooltip: 'Exchange rate between staking token and reward token.',
          placeholder: 'eg. 1',
          options: [],
        },
        {
          key: 'apr',
          title: 'APR',
          type: 'input',
          icon: '',
          value: '25%',
          tooltip: '',
          placeholder: 'eg. 20%',
          options: [],
        },
        {
          key: 'amount',
          title: 'Reward amount',
          type: 'input',
          icon: '',
          value: '0',
          tooltip: '',
          placeholder: 'eg. 100,000',
          options: [],
        },
      ],
    },
  },
];
