name: Docker develop build

on:
  push:
    branches:
      - 'develop'

jobs:
  build-bvm-website-develop:
    uses: TrustlessComputer/tc-github-action-templates/.github/workflows/docker-build-and-push.yaml@main
    with:
      DOCKER_IMAGE_NAME: bvm-website
      DOCKERFILE_NAME: Dockerfile
      CONCURRENCY_GROUP: docker_build_develop
      RUNNER_TAG: ubuntu-latest
    secrets:
      GCLOUD_DEV_SERVICE_ACCOUNT_JSON: ${{ secrets.GCLOUD_DEV_SERVICE_ACCOUNT_JSON }}
      SECRET_DEPLOY_GITHUB_USER: ${{ secrets.SECRET_DEPLOY_GITHUB_USER }}
      SECRET_DEPLOY_GITHUB_TOKEN: ${{ secrets.SECRET_DEPLOY_GITHUB_TOKEN }}
