name: Docker cache build

on:
  push:
    branches:
      - main

jobs:
  docker-cache:
    uses: TrustlessComputer/tc-github-action-templates/.github/workflows/docker-build-cache.yaml@main
    with:
      DOCKER_IMAGE_NAME: bvm-website
      DOCKERFILE_NAME: cache.Dockerfile
      SECRET_DEPLOY_GITHUB_USER: ${{ secrets.SECRET_DEPLOY_GITHUB_USER }}
      SECRET_DEPLOY_GITHUB_TOKEN: ${{ secrets.SECRET_DEPLOY_GITHUB_TOKEN }}

