name: Docker production build

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'

jobs:
  build-bvm-website-production:
    uses: TrustlessComputer/tc-github-action-templates/.github/workflows/docker-build-and-push.yaml@main
    with:
      DOCKER_IMAGE_NAME: bvm-website
      DOCKERFILE_NAME: Dockerfile
      CONCURRENCY_GROUP: docker_build_production
      RUNNER_TAG: ubuntu-latest
    secrets:
      GCLOUD_DEV_SERVICE_ACCOUNT_JSON: ${{ secrets.GCLOUD_DEV_SERVICE_ACCOUNT_JSON }}
